In [5]:
import pandas as pd
import numpy as np
from datafc import eloratings

In [6]:
cleaned_df = pd.read_csv("../data/cleaned/international_matches_clean.csv")

In [7]:
eloratings.country_matches_data("United_States")

,query_country,date,team_a,team_b,team_a_score,team_b_score,tournament,host,points,team_a_rating,team_b_rating,team_a_rank_change,team_b_rank_change,team_a_rank,team_b_rank
0,United_States,1916-08-20,SE,US,2,3,F,NaN,-11,1634,1711,-2.0,NaN,16,13
1,United_States,1916-09-03,NO,US,1,1,F,NaN,6,1377,1705,0.0,0.0,28,13
2,United_States,1924-05-25,US,EE,1,0,OG,FR,8,1713,1364,-1.0,-1.0,18,48
3,United_States,1924-05-29,UY,US,3,0,OG,FR,17,2014,1696,0.0,-4.0,1,22
4,United_States,1924-06-10,PL,US,2,3,F,NaN,-9,1557,1705,-1.0,3.0,36,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
828,United_States,2026-06-12,US,PY,4,1,WC,NaN,54,1780,1780,12.0,-4.0,26,26
829,United_States,2026-06-19,US,AU,2,0,WC,NaN,40,1820,1799,3.0,-3.0,23,26
830,United_States,2026-06-25,US,TR,2,3,WC,NaN,-39,1781,1852,-4.0,5.0,26,20
831,United_States,2026-07-01,US,BA,2,0,WC,NaN,17,1798,1605,1.0,-5.0,26,63
832,United_States,2026-07-06,US,BE,1,4,WC,NaN,-51,1747,1961,-6.0,3.0,31,10

In [8]:
usa = eloratings.country_matches_data("United_States")

usa_wc_row = usa[
    (usa["date"] == "2026-07-06") &
    (usa["team_a"] == "US") &
    (usa["team_b"] == "BE")
]

usa_wc_row

,query_country,date,team_a,team_b,team_a_score,team_b_score,tournament,host,points,team_a_rating,team_b_rating,team_a_rank_change,team_b_rank_change,team_a_rank,team_b_rank
832,United_States,2026-07-06,US,BE,1,4,WC,NaN,-51,1747,1961,-6.0,3.0,31,10

In [9]:
bel = eloratings.country_matches_data("Belgium")

bel_wc_row = bel[
    (bel["date"] == "2026-07-06") &
    (bel["team_a"] == "US") &
    (bel["team_b"] == "BE")
]

bel_wc_row

,query_country,date,team_a,team_b,team_a_score,team_b_score,tournament,host,points,team_a_rating,team_b_rating,team_a_rank_change,team_b_rank_change,team_a_rank,team_b_rank
882,Belgium,2026-07-06,US,BE,1,4,WC,NaN,-51,1747,1961,-6.0,3.0,31,10

In [10]:

print(usa_wc_row.T)
print()
print(bel_wc_row.T)

                                    832
query_country             United_States
date                2026-07-06 00:00:00
team_a                               US
team_b                               BE
team_a_score                          1
team_b_score                          4
tournament                           WC
host                                NaN
points                              -51
team_a_rating                      1747
team_b_rating                      1961
team_a_rank_change                 -6.0
team_b_rank_change                  3.0
team_a_rank                          31
team_b_rank                          10

                                    882
query_country                   Belgium
date                2026-07-06 00:00:00
team_a                               US
team_b                               BE
team_a_score                          1
team_b_score                          4
tournament                           WC
host                                NaN
points                              -51
team_a_rating                      1747
team_b_rating                      1961
team_a_rank_change                 -6.0
team_b_rank_change                  3.0
team_a_rank                          31
team_b_rank                          10

In [11]:
elo_name_map = {
    "Curaçao": "Curacao",
    "Czech Republic": "Czechia",
    "Republic of Ireland": "Ireland",
    "Timor-Leste": "East_Timor",
    'São Tomé and Príncipe': "Sao_Tome_and_Principe",
    "United States Virgin Islands": "US_Virgin_Islands"
}

In [12]:
countries = sorted(
    set(cleaned_df["home_team"]) |
    set(cleaned_df["away_team"])
)

all_matches = []
failed_countries = []

for country in countries:
    try:
        elo_country = elo_name_map.get(country, country) 
        elo_country = elo_country.replace(" ", "_")

        df = eloratings.country_matches_data(elo_country)
        all_matches.append(df)
        print(f"yep {country}")

    except Exception:
        print(f"nope {country}")
        failed_countries.append(country)

yep Afghanistan
yep Albania
yep Algeria
nope American Samoa
yep Andorra
yep Angola
yep Anguilla
yep Antigua and Barbuda
yep Argentina
yep Armenia
yep Aruba
yep Australia
yep Austria
yep Azerbaijan
yep Bahamas
yep Bahrain
yep Bangladesh
yep Barbados
yep Belarus
yep Belgium
yep Belize
yep Benin
yep Bermuda
yep Bhutan
yep Bolivia
yep Bosnia and Herzegovina
yep Botswana
yep Brazil
yep British Virgin Islands
yep Brunei
yep Bulgaria
yep Burkina Faso
yep Burundi
yep Cambodia
yep Cameroon
yep Canada
yep Cape Verde
yep Cayman Islands
yep Central African Republic
yep Chad
yep Chile
yep China
yep Colombia
yep Congo
yep Cook Islands
yep Costa Rica
yep Croatia
yep Cuba
yep Curaçao
yep Cyprus
yep Czech Republic
yep DR Congo
yep Denmark
yep Djibouti
yep Dominica
yep Dominican Republic
yep Ecuador
yep Egypt
yep El Salvador
yep England
yep Equatorial Guinea
yep Eritrea
yep Estonia
yep Eswatini
yep Ethiopia
yep Fiji
yep Finland
yep France
yep Gabon
yep Gambia
yep Georgia
yep Germany
yep Ghana
yep Gibraltar
yep Greece
yep Grenada
yep Guam
yep Guatemala
yep Guinea
yep Guinea-Bissau
yep Guyana
yep Haiti
yep Honduras
yep Hong Kong
yep Hungary
yep Iceland
yep India
yep Indonesia
yep Iran
yep Iraq
yep Israel
yep Italy
yep Ivory Coast
yep Jamaica
yep Japan
yep Jordan
yep Kazakhstan
yep Kenya
yep Kuwait
yep Kyrgyzstan
yep Laos
yep Latvia
yep Lebanon
yep Lesotho
yep Liberia
yep Libya
yep Liechtenstein
yep Lithuania
yep Luxembourg
yep Madagascar
yep Malawi
yep Malaysia
yep Maldives
yep Mali
yep Malta
yep Mauritius
yep Mexico
yep Moldova
yep Mongolia
yep Montenegro
yep Montserrat
yep Morocco
yep Mozambique
yep Myanmar
yep Namibia
yep Nepal
yep Netherlands
yep New Caledonia
yep New Zealand
yep Nicaragua
yep Niger
yep Nigeria
yep North Korea
yep North Macedonia
yep Northern Ireland
yep Norway
yep Oman
yep Pakistan
yep Palestine
yep Panama
yep Paraguay
yep Peru
yep Philippines
yep Poland
yep Portugal
yep Puerto Rico
yep Qatar
yep Republic of Ireland
yep Romania
yep Russia
yep Rwanda
yep Saint Kitts and Nevis
yep Saint Lucia
yep Saint Vincent and the Grenadines
yep Samoa
yep San Marino
yep Saudi Arabia
yep Scotland
yep Senegal
yep Serbia
yep Seychelles
yep Sierra Leone
yep Singapore
yep Slovakia
yep Slovenia
yep Solomon Islands
yep Somalia
yep South Africa
yep South Korea
yep South Sudan
yep Spain
yep Sri Lanka
yep Sudan
yep Suriname
yep Sweden
yep Switzerland
yep Syria
yep São Tomé and Príncipe
yep Taiwan
yep Tajikistan
yep Tanzania
yep Thailand
yep Timor-Leste
yep Togo
yep Tonga
yep Trinidad and Tobago
yep Tunisia
yep Turkey
yep Turkmenistan
yep Turks and Caicos Islands
yep Uganda
yep Ukraine
yep United Arab Emirates
yep United States
yep United States Virgin Islands
yep Uruguay
yep Uzbekistan
yep Vanuatu
yep Venezuela
yep Vietnam
yep Wales
yep Yemen
yep Zambia
yep Zimbabwe

In [13]:
print(failed_countries)

['American Samoa']

In [14]:
country = "American Samoa"

print(repr(country))
print(repr(country.strip()))
print(country == "American Samoa")

'American Samoa'
'American Samoa'
True

In [15]:
print(len(all_matches))

203

In [16]:
codes = eloratings.country_codes_data()

print(codes.tail(20))

    country_code       country_name
284           UY            Uruguay
285           VI  US Virgin Islands
286           US      United States
287           SU       Soviet Union
288           UZ         Uzbekistan
289           VU            Vanuatu
290           VA            Vatican
291           VE          Venezuela
292           VN            Vietnam
293           WA              Wales
294           WF  Wallis and Futuna
295           WG       West Germany
296           EH     Western Sahara
297           WM      Western Samoa
298           YE              Yemen
299           YU         Yugoslavia
300           ZR              Zaire
301           ZM             Zambia
302           ZN           Zanzibar
303           ZW           Zimbabwe

In [28]:
elo_matches = pd.concat(all_matches, ignore_index = True)

In [27]:
elo_matches.shape

(100970, 10)

In [19]:
elo_matches.isnull().sum()

query_country             0
date                    432
team_a                    0
team_b                    0
team_a_score              0
team_b_score              0
tournament                0
host                  75235
points                    0
team_a_rating             0
team_b_rating             0
team_a_rank_change      300
team_b_rank_change      312
team_a_rank             112
team_b_rank              83
dtype: int64

In [29]:
elo_matches.to_csv(
    "../data/raw/elo_setup_old.csv",
    index = False
) ####

In [30]:
elo_matches["query_country"].nunique()

203

In [31]:
elo_matches.columns

Index(['query_country', 'date', 'team_a', 'team_b', 'team_a_score',
       'team_b_score', 'tournament', 'host', 'points', 'team_a_rating',
       'team_b_rating', 'team_a_rank_change', 'team_b_rank_change',
       'team_a_rank', 'team_b_rank'],
      dtype='object')

In [ ]:

elo_matches.to_csv(
    "../data/raw/elo_setup_new.csv",
    index = False
) ####

In [33]:
elo_matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100970 entries, 0 to 100969
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   date           100538 non-null  datetime64[ns]
 1   team_a         100970 non-null  object
 2   team_b         100970 non-null  object
 3   team_a_score   100970 non-null  int64
 4   team_b_score   100970 non-null  int64
 5   tournament     100970 non-null  object
 6   team_a_rating  100970 non-null  int64
 7   team_b_rating  100970 non-null  int64
 8   team_a_rank    100858 non-null  float64
 9   team_b_rank    100887 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(4), object(3)
memory usage: 7.7+ MB

In [36]:
elo_matches.duplicated().sum()

np.int64(48950)

In [39]:
elo_matches = elo_matches.drop_duplicates() 
elo_matches.duplicated().sum()

np.int64(0)

In [40]:
elo_matches.shape

(52020, 10)

In [ ]:
elo_matches.info()

<class 'pandas.core.frame.DataFrame'>
Index: 52020 entries, 0 to 100942
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           51761 non-null  datetime64[ns]
 1   team_a         52020 non-null  object
 2   team_b         52020 non-null  object
 3   team_a_score   52020 non-null  int64
 4   team_b_score   52020 non-null  int64
 5   tournament     52020 non-null  object
 6   team_a_rating  52020 non-null  int64
 7   team_b_rating  52020 non-null  int64
 8   team_a_rank    51963 non-null  float64
 9   team_b_rank    51975 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(4), object(3)
memory usage: 4.4+ MB

In [47]:
(elo_matches == 0).sum()

date                 0
team_a               0
team_b               0
team_a_score      9960
team_b_score     22064
tournament           0
team_a_rating        0
team_b_rating        0
team_a_rank          0
team_b_rank          0
dtype: int64

In [43]:
elo_matches["tournament"].unique()

array(['IND', 'F', 'OG', 'ASG', 'OQ', 'SQ', 'RDC', 'GLT', 'SFF', 'WQ',
       'FRC', 'ACH', 'SCQ', 'SQC', 'MRD', 'WQS', 'AIM', 'CNU', 'FT',
       'DJB', 'BLK', 'BCE', 'EQ', 'PMC', 'EC', 'ENC', 'ENB', 'DBT', 'AGQ',
       'AFG', 'FQ', 'MDG', 'AR', 'N1C', 'EDT', 'PAL', 'KUN', 'NOA', 'TIF',
       'WC', 'FRT', 'PAR', 'IPC', 'ARQ', 'ARC', 'FRH', 'AAC', 'N7C',
       'BLA', 'WQA', 'FFS', 'ALM', 'END', 'ZVT', 'CFG', 'ACG', 'SDC',
       'CSF', 'LIT', 'CRQ', 'FCQ', 'CBQ', 'FBQ', 'CLQ', 'CLC', 'PEL',
       'CFS', 'WCQ', 'CUC', 'CUQ', 'CAC', 'OEC', 'CBC', 'FQC', 'WUC',
       'CCQ', 'CLG', 'FQB', 'PBC', 'PRC', 'CLB', 'LPT', 'NWT', 'POA',
       'MR', 'POU', 'MTV', 'SZP', 'CCP', 'ROC', 'SA', 'RCH', 'LPC', 'RCB',
       'FMC', 'CYC', 'LPR', 'BAC', 'ACD', 'UAC', 'HGC', 'JMC', 'CPR',
       'APR', 'PAC', 'ATL', 'RCO', 'CDC', 'CON', 'BRI', 'HHC', 'RCC',
       'SVC', 'CA', 'CDM', 'ATB', 'ATR', 'ALP', 'ATN', 'BGD', 'MND',
       'NGC', 'AGC', 'KRN', 'IC', 'ACT', 'AFT', 'SLT', 'NMC', 'CDB',
       'BAP', 'CFA', 'RBK', 'ZHC', 'CC', 'BAL', 'CHC', 'TOI', 'NLC',
       'FCS', 'ADI', 'TCC', 'AMB', 'EBC', 'HOC', 'WCO', 'GBT', 'CCF',
       'ABC', 'ABS', 'ASH', 'VIC', 'OC', 'MRL', 'TTC', 'AMP', 'PRS',
       'OCT', 'SMB', 'OPS', 'CVP', 'AOC', 'WQO', 'AC', 'EAQ', 'EAH',
       'WGN', 'DGC', 'CTS', 'ENA', 'EAB', 'ECO', 'PLG', 'ATV', 'INC',
       'PAG', 'PAQ', 'GLF', 'ARR', 'WAG', 'WAH', 'KNG', 'PRG', 'SAG',
       'NPC', 'GJC', 'MLM', 'JWM', 'GCH', 'BGC', 'PMT', 'MS', 'FRY',
       'DNT', 'CRC', 'WIT', 'EVE', 'CCL', 'LGC', 'ECT', 'VDA', 'RNC',
       'LVC', 'KHC', 'ENL', 'NQU', 'NUQ', 'NQC', 'CCC', 'CCH', 'JAM',
       'NKR', 'JCM', 'WAN', 'COQ', 'SLD', 'ACC', 'TFC', 'IG', 'CLA',
       'ANF', 'SGC', 'BG', 'CPC', 'SCR', 'PVC', 'JRC', 'USC', 'PCC',
       'DNH', 'BLR', 'KMC', 'MKR', 'RAC', 'RBC', 'OCC', 'OHC', 'JCS',
       'EGM', 'ARB', 'ATC', 'BIC', 'RSC', 'TXR', 'UMB', 'CBG', 'SEG',
       'ING', 'SEA', 'SEQ', 'ASC', 'NTC', 'COC', 'FPG', 'ECW', 'BST',
       'GRC', 'WFQ', 'AAG', 'UTC', 'CGL', 'CEC', 'NBT', 'THU', 'SEP',
       'GNF', 'JAT', 'TRP', 'AQC', 'UDE', 'WQC', 'MIA', 'SMC', 'NAC',
       'CBS', 'SKD', 'CAN', 'CBN', 'CNL', 'CAQ', 'CDS', 'WUS', 'UFC',
       'CMC', 'PCF', 'CPD', 'SAQ', 'BQR', 'CNY', 'CHN', 'FEG', 'OIC',
       'LNY', 'GWC', 'DNS', 'ACV', 'PHL', 'DBC', 'FCC', 'GJQ', 'BDW',
       'ETF', 'SBA', 'IOT', 'SPG', 'OCP', 'WOQ', 'WOS', 'OQG', 'PG',
       'OCQ', 'JCN', 'CAG', 'JSC', 'RVC', 'KOR', 'UNC', 'CAI', 'ANT',
       'NSM', 'MJT', 'FFC', 'WQN', 'BQS', 'RMA', 'GSC', 'DNR', 'GBS',
       'HEC', 'PSC', 'DVC', 'IEC', 'CHP', 'SLV', 'EBN', 'BKG', 'MVC',
       'BRT', 'RVA', 'LGR', 'NRD', 'ON', 'SCN', 'WQD', 'CIQ', 'CIB',
       'GWT', 'BRG', 'MFT', 'EMC', 'MDC', 'PGC', 'CRO', 'HRT', 'CSM',
       'DLT', 'BC', 'WQB', 'EQB', 'WPC', 'MAZ', 'AZT', 'CMS', 'BLC', 'TT',
       'BLT', 'HCM', 'MRS', 'BSE', 'RTR', 'TCH', 'EAC', 'SPM', 'MLN',
       'OCM', 'PMG', 'LHT', 'COR', 'AQW', 'AWA', 'WAC', 'WFU', 'PTR',
       'CNT', 'JLC', 'AKC', 'AZK', 'UHR', 'FRG', 'ACS', 'PNF', 'MWC',
       'ECD', 'MNG', 'EQM', 'MRN', 'MRC', 'PST', 'BLW', 'SKS', 'SMD',
       'PFT', 'WTC', 'AMO', 'BBC', 'HET', 'MGC', 'FFT', 'DCS', 'FQP',
       'RJC', 'AHM', 'TGF', 'LTC', 'AYA', 'DNC', 'GRN', 'CLM', 'MHC',
       'INL', 'VFF', 'TGC', 'NKB', 'GRD', 'RCD', 'VLM', 'RPB', 'KPV',
       'BPT', 'EAM', 'ADC', 'CAU', 'GSG', 'TRE', 'JKC', 'ECA', 'SAT',
       'IOC', 'ANN', 'GCC', 'NRZ', 'WQL', 'MRU', 'ILG', 'LYN', 'BGZ',
       'IOG', 'AFD', 'SMT', 'OVC', 'CWY', 'CSW', 'BFC', 'SAS', 'CCB',
       'CMZ', 'CCN', 'GCT', 'CML', 'CFC', 'EAG', 'KWT', 'HGG', 'SPC',
       'FRN', 'TGB', 'OSN', 'TLC', 'EQN', 'BOC', 'TPC', 'ART', 'ATA',
       'MFP', 'PDR', 'EIC', 'IPF', 'KPC', 'UCT', 'KAC', 'KCC', 'DKM',
       'PRD', 'RUC', 'MKS', 'WTK', 'OCH', 'TFT', 'HRS', 'PLR', 'RMD',
       'EIE', 'LVY', 'RCT', 'CRR'], dtype=object)