In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("../data/raw/elo_setup_new.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52019 entries, 0 to 52018
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                51760 non-null  object
 1   team_a              51885 non-null  object
 2   team_b              51849 non-null  object
 3   team_a_score        52019 non-null  int64
 4   team_b_score        52019 non-null  int64
 5   tournament          52019 non-null  object
 6   host                13377 non-null  object
 7   points              52019 non-null  int64
 8   team_a_rating       52019 non-null  int64
 9   team_b_rating       52019 non-null  int64
 10  team_a_rank_change  51863 non-null  float64
 11  team_b_rank_change  51846 non-null  float64
 12  team_a_rank         51962 non-null  float64
 13  team_b_rank         51974 non-null  float64
dtypes: float64(4), int64(5), object(5)
memory usage: 5.6+ MB

In [4]:
df.head(5)

,date,team_a,team_b,team_a_score,team_b_score,tournament,host,points,team_a_rating,team_b_rating,team_a_rank_change,team_b_rank_change,team_a_rank,team_b_rank
0,1941-08-24,AF,IR,1,0,IND,NaN,29,929,1571,NaN,NaN,96.0,45.0
1,1948-06-03,IN,AF,4,0,F,NaN,0,1658,929,0.0,0.0,32.0,106.0
2,1948-07-26,LU,AF,6,0,OG,EN,14,1307,915,2.0,0.0,84.0,107.0
3,1949-10-26,IR,AF,4,0,F,NaN,0,1571,915,0.0,0.0,44.0,112.0
4,1951-03-07,IN,AF,3,0,ASG,NaN,1,1669,914,0.0,0.0,29.0,114.0

In [5]:
df = df.drop(columns = ["host", "team_a_rank_change", "team_b_rank_change", "points"])

In [6]:
df.isnull().sum()

date             259
team_a           134
team_b           170
team_a_score       0
team_b_score       0
tournament         0
team_a_rating      0
team_b_rating      0
team_a_rank       57
team_b_rank       45
dtype: int64

In [7]:
df[df.isna().any(axis=1)]

,date,team_a,team_b,team_a_score,team_b_score,tournament,team_a_rating,team_b_rating,team_a_rank,team_b_rank
168,1946-08-22,AL,ME,5,0,F,1619,1671,39.0,NaN
192,NaN,AL,CN,4,1,F,1579,1520,49.0,63.0
585,NaN,TN,DZ,0,4,F,1560,1729,55.0,24.0
588,NaN,LY,DZ,0,7,F,1417,1761,87.0,20.0
636,NaN,SD,DZ,2,0,EDT,1678,1606,37.0,50.0
...,...,...,...,...,...,...,...,...,...,...
51919,NaN,ZD,ND,4,0,F,1505,1596,54.0,39.0
51920,NaN,ND,ZD,3,2,F,1597,1500,37.0,57.0
51922,NaN,ND,ZD,1,4,F,1566,1515,47.0,55.0
51930,NaN,ZD,ND,4,2,LVY,1569,1532,58.0,54.0
51931,NaN,ZD,ND,0,2,LVY,1538,1563,58.0,54.0

In [8]:
cols = [
    "date",
    "team_a",
    "team_b",
    "team_a_rank",
    "team_b_rank"
]

null_rows = df[cols].isnull().any(axis=1)

print(null_rows.sum())
display(df.loc[null_rows].head(20) )

622

,date,team_a,team_b,team_a_score,team_b_score,tournament,team_a_rating,team_b_rating,team_a_rank,team_b_rank
168,1946-08-22,AL,ME,5,0,F,1619,1671,39.0,NaN
192,NaN,AL,CN,4,1,F,1579,1520,49.0,63.0
585,NaN,TN,DZ,0,4,F,1560,1729,55.0,24.0
588,NaN,LY,DZ,0,7,F,1417,1761,87.0,20.0
636,NaN,SD,DZ,2,0,EDT,1678,1606,37.0,50.0
981,2001-01-26,DZ,NaN,1,0,WQ,1521,1315,72.0,125.0
989,2001-06-30,NaN,DZ,0,4,WQ,1290,1514,132.0,71.0
1001,2002-09-07,NaN,DZ,0,1,FQ,1198,1488,156.0,80.0
1009,2003-06-20,DZ,NaN,1,0,FQ,1498,1174,76.0,158.0
1495,NaN,AO,MZ,3,3,F,1488,1312,72.0,115.0
1504,NaN,AO,MZ,4,2,F,1481,1344,76.0,96.0
1505,NaN,AO,MZ,1,2,F,1465,1360,76.0,96.0
1506,NaN,MZ,AO,2,0,F,1375,1450,96.0,76.0
1592,1989-05-16,NaN,AO,0,1,F,1195,1476,140.0,75.0
1617,1994-09-04,AO,NaN,2,0,FQ,1420,1117,95.0,168.0
1622,1995-04-08,NaN,AO,2,2,FQ,1149,1414,164.0,99.0
1646,1998-02-12,AO,NaN,3,3,AR,1523,1362,70.0,118.0
1650,1998-05-30,NaN,AO,1,1,CSF,1331,1490,124.0,79.0
1664,1999-09-26,AO,NaN,1,0,CSF,1482,1316,82.0,128.0
1665,1999-10-02,NaN,AO,1,1,CSF,1320,1478,126.0,82.0

In [9]:
df = df.dropna(subset = ["team_a", "team_a_rank", "team_b_rank", "team_b", "date"])
df.isnull().sum()

date             0
team_a           0
team_b           0
team_a_score     0
team_b_score     0
tournament       0
team_a_rating    0
team_b_rating    0
team_a_rank      0
team_b_rank      0
dtype: int64

In [10]:
df["date"] = pd.to_datetime(df["date"])

categorical = [
    "tournament",
    "team_a",
    "team_b"
]

for col in categorical:
    df[col] = df[col].astype("category")
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 51397 entries, 0 to 52018
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           51397 non-null  datetime64[ns]
 1   team_a         51397 non-null  category
 2   team_b         51397 non-null  category
 3   team_a_score   51397 non-null  int64
 4   team_b_score   51397 non-null  int64
 5   tournament     51397 non-null  category
 6   team_a_rating  51397 non-null  int64
 7   team_b_rating  51397 non-null  int64
 8   team_a_rank    51397 non-null  float64
 9   team_b_rank    51397 non-null  float64
dtypes: category(3), datetime64[ns](1), float64(2), int64(4)
memory usage: 3.5 MB

In [11]:
df.head(5)

,date,team_a,team_b,team_a_score,team_b_score,tournament,team_a_rating,team_b_rating,team_a_rank,team_b_rank
0,1941-08-24,AF,IR,1,0,IND,929,1571,96.0,45.0
1,1948-06-03,IN,AF,4,0,F,1658,929,32.0,106.0
2,1948-07-26,LU,AF,6,0,OG,1307,915,84.0,107.0
3,1949-10-26,IR,AF,4,0,F,1571,915,44.0,112.0
4,1951-03-07,IN,AF,3,0,ASG,1669,914,29.0,114.0

In [12]:
df[ 
df.duplicated(
    subset=["date", "team_a", "team_b"],
    keep = False
)
].sort_values(["date", "team_a", "team_b"])

,date,team_a,team_b,team_a_score,team_b_score,tournament,team_a_rating,team_b_rating,team_a_rank,team_b_rank
24370,2022-03-08,SW,LS,0,0,F,1238,1205,146.0,159.0
24371,2022-03-08,SW,LS,4,0,F,1250,1193,146.0,159.0
24381,2023-06-03,SW,LS,1,2,F,1284,1233,138.0,155.0
24382,2023-06-03,SW,LS,1,0,F,1290,1227,138.0,155.0

In [13]:
df.describe()

,date,team_a_score,team_b_score,team_a_rating,team_b_rating,team_a_rank,team_b_rank
count,51397,51397.000000,51397.000000,51397.000000,51397.000000,51397.000000,51397.000000
mean,1993-05-14 02:57:47.828861568,1.931163,0.987120,1550.415219,1505.041170,70.444909,78.530848
min,1872-11-30 00:00:00,0.000000,0.000000,369.000000,334.000000,1.000000,1.000000
25%,1978-07-18 00:00:00,1.000000,0.000000,1373.000000,1323.000000,27.000000,30.000000
50%,1999-05-16 00:00:00,2.000000,1.000000,1563.000000,1529.000000,60.000000,67.000000
75%,2012-12-20 00:00:00,3.000000,1.000000,1744.000000,1719.000000,105.000000,118.000000
max,2026-07-19 00:00:00,31.000000,15.000000,2259.000000,2203.000000,243.000000,244.000000
std,NaN,1.796307,1.201063,275.594159,300.154619,53.069656,57.496490

In [14]:
df["tournament"].value_counts()

tournament
F      17184
WQ      7851
EQ      2824
FQ      2345
WC      1068
       ...
BSE        1
PDR        1
CAI        1
CCB        1
CCN        1
Name: count, Length: 489, dtype: int64

In [15]:
df = df.reset_index(drop = True)

In [16]:
df.to_csv("../data/cleaned/elo_ratings.csv")