In [1]:
import pandas as pd
import numpy as np

In [2]:
matches = pd.read_csv("../data/processed/matches_elo_merged_processed.csv")

In [3]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34549 entries, 0 to 34548
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       34549 non-null  int64
 1   date             34549 non-null  object
 2   home_team        34549 non-null  object
 3   away_team        34549 non-null  object
 4   home_score       34549 non-null  float64
 5   away_score       34549 non-null  float64
 6   city             34549 non-null  object
 7   country          34549 non-null  object
 8   neutral          34549 non-null  bool
 9   tournament_code  29840 non-null  object
 10  tournament       29840 non-null  object
 11  home_elo         29840 non-null  float64
 12  away_elo         29840 non-null  float64
 13  home_ranking     29840 non-null  float64
 14  away_ranking     29840 non-null  float64
dtypes: bool(1), float64(6), int64(1), object(7)
memory usage: 3.7+ MB

In [4]:
matches = matches.drop(columns = "Unnamed: 0")

In [5]:
matches["elo_difference"] = (matches["home_elo"] -  matches["away_elo"])

matches["rank_difference"] = (matches["away_ranking"] - matches["home_ranking"])

matches["home_win"] = np.where(matches["home_score"] > matches["away_score"], 1, 0)
matches["home_loss"] = np.where(matches["home_score"] < matches["away_score"], 1, 0)
matches["home_draw"] = np.where(matches["home_score"] == matches["away_score"], 1, 0)

matches["away_win"] = np.where(matches["away_score"] > matches["home_score"], 1, 0)
matches["away_loss"] = np.where(matches["away_score"] < matches["home_score"], 1, 0)
matches["away_draw"] = np.where(matches["home_score"] == matches["away_score"], 1, 0)

In [6]:
matches.tail(10)

,date,home_team,away_team,home_score,away_score,city,country,neutral,tournament_code,tournament,...,home_ranking,away_ranking,elo_difference,rank_difference,home_win,home_loss,home_draw,away_win,away_loss,away_draw
34539,2026-07-07,Argentina,Egypt,3.0,2.0,Atlanta,United States,True,WC,FIFA World Cup,...,2.0,34.0,414.0,32.0,1,0,0,0,1,0
34540,2026-07-07,Switzerland,Colombia,0.0,0.0,Vancouver,Canada,True,WC,FIFA World Cup,...,11.0,5.0,-54.0,-6.0,0,0,1,0,0,1
34541,2026-07-09,France,Morocco,2.0,0.0,Foxborough,United States,True,WC,FIFA World Cup,...,2.0,14.0,262.0,12.0,1,0,0,0,1,0
34542,2026-07-10,Spain,Belgium,2.0,1.0,Inglewood,United States,True,WC,FIFA World Cup,...,1.0,11.0,242.0,10.0,1,0,0,0,1,0
34543,2026-07-11,Norway,England,1.0,2.0,Miami Gardens,United States,True,WC,FIFA World Cup,...,9.0,4.0,-146.0,-5.0,0,1,0,1,0,0
34544,2026-07-11,Argentina,Switzerland,3.0,1.0,Kansas City,United States,True,WC,FIFA World Cup,...,2.0,11.0,249.0,9.0,1,0,0,0,1,0
34545,2026-07-14,France,Spain,0.0,2.0,Arlington,United States,True,WC,FIFA World Cup,...,3.0,1.0,-111.0,-2.0,0,1,0,1,0,0
34546,2026-07-15,England,Argentina,1.0,2.0,Atlanta,United States,True,WC,FIFA World Cup,...,4.0,2.0,-126.0,-2.0,0,1,0,1,0,0
34547,2026-07-18,France,England,4.0,6.0,Miami Gardens,United States,True,WC,FIFA World Cup,...,4.0,3.0,-55.0,-1.0,0,1,0,1,0,0
34548,2026-07-19,Spain,Argentina,1.0,0.0,East Rutherford,United States,True,WC,FIFA World Cup,...,1.0,2.0,86.0,1.0,1,0,0,0,1,0

In [7]:
matches[[
    "home_team", "home_score",
    "away_team", "away_score", 
    "home_win", "home_loss",
    "home_draw", "away_win",
    "away_loss", "away_draw"
]].tail(15)

,home_team,home_score,away_team,away_score,home_win,home_loss,home_draw,away_win,away_loss,away_draw
34534,Paraguay,0.0,France,1.0,0,1,0,1,0,0
34535,Brazil,1.0,Norway,2.0,0,1,0,1,0,0
34536,Mexico,2.0,England,3.0,0,1,0,1,0,0
34537,Portugal,0.0,Spain,1.0,0,1,0,1,0,0
34538,United States,1.0,Belgium,4.0,0,1,0,1,0,0
34539,Argentina,3.0,Egypt,2.0,1,0,0,0,1,0
34540,Switzerland,0.0,Colombia,0.0,0,0,1,0,0,1
34541,France,2.0,Morocco,0.0,1,0,0,0,1,0
34542,Spain,2.0,Belgium,1.0,1,0,0,0,1,0
34543,Norway,1.0,England,2.0,0,1,0,1,0,0
34544,Argentina,3.0,Switzerland,1.0,1,0,0,0,1,0
34545,France,0.0,Spain,2.0,0,1,0,1,0,0
34546,England,1.0,Argentina,2.0,0,1,0,1,0,0
34547,France,4.0,England,6.0,0,1,0,1,0,0
34548,Spain,1.0,Argentina,0.0,1,0,0,0,1,0

In [10]:
matches_helper_home = matches.copy()
matches_helper_away = matches.copy() 

matches_helper_home = matches_helper_home.drop(columns=[
    "city", "country", "neutral", "tournament_code", 
    "tournament", "home_elo", "away_elo", "home_ranking",
    "away_ranking", "away_win", "away_loss", "away_draw",
    "elo_difference", "rank_difference"])

matches_helper_away = matches_helper_away.drop(columns=[
    "city", "country", "neutral", "tournament_code", 
    "tournament", "home_elo", "away_elo", "home_ranking",
    "away_ranking", "home_win", "home_loss", "home_draw",
    "elo_difference", "rank_difference"])


matches_helper_home = matches_helper_home.rename(columns={"home_team": "team", "away_team": "opponent", "home_score": "goals_for", 
                                                          "away_score": "goals_against", "home_win": "win", 
                                                          "home_draw": "draw", "home_loss": "loss"})


matches_helper_away = matches_helper_away.rename(columns={"away_team": "team", "home_team": "opponent", "away_score": "goals_for", 
                                                          "home_score": "goals_against", "away_win": "win", 
                                                          "away_draw": "draw", "away_loss": "loss"})


matches_helper_home.tail(5)

,date,team,opponent,goals_for,goals_against,win,loss,draw
34544,2026-07-11,Argentina,Switzerland,3.0,1.0,1,0,0
34545,2026-07-14,France,Spain,0.0,2.0,0,1,0
34546,2026-07-15,England,Argentina,1.0,2.0,0,1,0
34547,2026-07-18,France,England,4.0,6.0,0,1,0
34548,2026-07-19,Spain,Argentina,1.0,0.0,1,0,0

In [11]:
matches_helper_away.tail(5)

,date,opponent,team,goals_against,goals_for,win,loss,draw
34544,2026-07-11,Argentina,Switzerland,3.0,1.0,0,1,0
34545,2026-07-14,France,Spain,0.0,2.0,1,0,0
34546,2026-07-15,England,Argentina,1.0,2.0,1,0,0
34547,2026-07-18,France,England,4.0,6.0,1,0,0
34548,2026-07-19,Spain,Argentina,1.0,0.0,0,1,0

In [20]:
print(matches_helper_away.shape)
print(matches_helper_home.shape)

(34549, 8)
(34549, 8)

In [15]:
matches_helper_combined = pd.concat([matches_helper_home, matches_helper_away], ignore_index  = True)

matches_helper_combined = matches_helper_combined.sort_values(by=["team", "date"])

matches_helper_combined.tail(20)

,date,team,opponent,goals_for,goals_against,win,loss,draw
67561,2024-06-11,Zimbabwe,South Africa,1.0,3.0,0,1,0
67728,2024-09-06,Zimbabwe,Kenya,0.0,0.0,0,0,1
33234,2024-09-10,Zimbabwe,Cameroon,0.0,0.0,0,0,1
67790,2024-10-10,Zimbabwe,Namibia,1.0,0.0,1,0,0
33287,2024-10-14,Zimbabwe,Namibia,3.0,1.0,1,0,0
33361,2024-11-15,Zimbabwe,Kenya,1.0,1.0,0,0,1
67959,2024-11-19,Zimbabwe,Cameroon,1.0,2.0,0,1,0
33448,2025-03-20,Zimbabwe,Benin,2.0,2.0,0,0,1
68100,2025-03-25,Zimbabwe,Nigeria,1.0,1.0,0,0,1
33618,2025-06-06,Zimbabwe,Burkina Faso,0.0,2.0,0,1,0
68235,2025-06-10,Zimbabwe,Niger,1.0,1.0,0,0,1
68341,2025-09-05,Zimbabwe,Benin,0.0,1.0,0,1,0
33871,2025-09-09,Zimbabwe,Rwanda,0.0,1.0,0,1,0
68503,2025-10-10,Zimbabwe,South Africa,0.0,0.0,0,0,1
68547,2025-10-13,Zimbabwe,Lesotho,0.0,1.0,0,1,0
68609,2025-11-13,Zimbabwe,Algeria,1.0,3.0,0,1,0
68678,2025-11-17,Zimbabwe,Qatar,2.0,1.0,1,0,0
68734,2025-12-22,Zimbabwe,Egypt,1.0,2.0,0,1,0
68744,2025-12-26,Zimbabwe,Angola,1.0,1.0,0,0,1
34207,2025-12-29,Zimbabwe,South Africa,2.0,3.0,0,1,0

In [22]:
matches_helper_combined.head(5)

,date,team,opponent,goals_for,goals_against,win,loss,draw
1483,1941-08-10,Afghanistan,India,1.0,3.0,0,1,0
36609,1950-10-26,Afghanistan,Iran,0.0,4.0,0,1,0
40528,1975-04-02,Afghanistan,Saudi Arabia,0.0,2.0,0,1,0
40529,1975-04-04,Afghanistan,Iraq,0.0,4.0,0,1,0
40535,1975-04-06,Afghanistan,Qatar,1.0,2.0,0,1,0

In [35]:
matches_helper_combined["prev_win"] = matches_helper_combined.groupby(["team"])["win"].shift(1)
matches_helper_combined["last_5_win_rate"] = matches_helper_combined.groupby(["team"])["prev_win"].rolling(window=5).mean().reset_index(level=0, drop = True)


matches_helper_combined["prev_loss"] = matches_helper_combined.groupby(["team"])["loss"].shift(1)
matches_helper_combined["last_5_loss_rate"] = matches_helper_combined.groupby(["team"])["prev_loss"].rolling(window=5).mean().reset_index(level=0, drop = True)

matches_helper_combined["prev_goals_for"] = matches_helper_combined.groupby(["team"])["goals_for"].shift(1)
matches_helper_combined["last_5_scoring_rate"] = matches_helper_combined.groupby(["team"])["prev_goals_for"].rolling(window=5).mean().reset_index(level=0, drop = True)


matches_helper_combined["prev_goals_against"] = matches_helper_combined.groupby(["team"])["goals_against"].shift(1)
matches_helper_combined["last_5_conceding_rate"] = matches_helper_combined.groupby(["team"])["prev_goals_against"].rolling(window=5).mean().reset_index(level=0, drop = True)

In [38]:
matches_helper_combined.loc[matches_helper_combined["team"] == "France", ["date", "team", "opponent", "win", "last_5_win_rate", "last_5_loss_rate", "last_5_scoring_rate", "last_5_conceding_rate"]].tail(20)

,date,team,opponent,win,last_5_win_rate,last_5_loss_rate,last_5_scoring_rate,last_5_conceding_rate
67678,2024-07-05,France,Portugal,0,0.4,0.0,0.6,0.2
67684,2024-07-09,France,Spain,0,0.4,0.0,0.6,0.2
68354,2025-09-05,France,Ukraine,1,0.2,0.2,0.6,0.6
33882,2025-09-09,France,Iceland,1,0.4,0.2,1.0,0.6
33962,2025-10-10,France,Azerbaijan,1,0.6,0.2,1.2,0.6
68557,2025-10-13,France,Iceland,0,0.6,0.2,1.6,0.6
34071,2025-11-13,France,Ukraine,1,0.6,0.2,2.0,1.0
68668,2025-11-16,France,Azerbaijan,1,0.8,0.0,2.6,0.6
68790,2026-03-26,France,Brazil,1,0.8,0.0,2.8,0.8
68830,2026-03-29,France,Colombia,1,0.8,0.0,2.8,0.8
34364,2026-06-04,France,Ivory Coast,0,0.8,0.0,2.8,1.0
34421,2026-06-08,France,Northern Ireland,1,0.8,0.2,2.6,1.0
34461,2026-06-16,France,Senegal,1,0.8,0.2,2.4,1.2
34485,2026-06-22,France,Iraq,1,0.8,0.2,2.4,1.2
69058,2026-06-26,France,Norway,1,0.8,0.2,2.6,1.0
34522,2026-06-30,France,Sweden,1,0.8,0.2,2.8,1.0
69083,2026-07-04,France,Paraguay,1,1.0,0.0,3.2,0.6
34541,2026-07-09,France,Morocco,1,1.0,0.0,2.8,0.4
34545,2026-07-14,France,Spain,0,1.0,0.0,2.6,0.2
34547,2026-07-18,France,England,0,0.8,0.2,2.0,0.6

In [37]:
matches_helper_combined.head(30)

,date,team,opponent,goals_for,goals_against,win,loss,draw,prev_win,win_rate,last_5_win_rate,prev_loss,last_5_loss_rate,prev_goals_for,last_5_scoring_rate,prev_goals_against,last_5_conceding_rate
1483,1941-08-10,Afghanistan,India,1.0,3.0,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36609,1950-10-26,Afghanistan,Iran,0.0,4.0,0,1,0,0.0,NaN,NaN,1.0,NaN,1.0,NaN,3.0,NaN
40528,1975-04-02,Afghanistan,Saudi Arabia,0.0,2.0,0,1,0,0.0,NaN,NaN,1.0,NaN,0.0,NaN,4.0,NaN
40529,1975-04-04,Afghanistan,Iraq,0.0,4.0,0,1,0,0.0,NaN,NaN,1.0,NaN,0.0,NaN,2.0,NaN
40535,1975-04-06,Afghanistan,Qatar,1.0,2.0,0,1,0,0.0,NaN,NaN,1.0,NaN,0.0,NaN,4.0,NaN
40537,1975-04-10,Afghanistan,Saudi Arabia,0.0,6.0,0,1,0,0.0,0.0,0.0,1.0,1.0,1.0,0.4,2.0,3.0
40539,1975-04-12,Afghanistan,Qatar,1.0,1.0,0,0,1,0.0,0.0,0.0,1.0,1.0,0.0,0.2,6.0,3.6
40543,1975-04-14,Afghanistan,Iraq,1.0,3.0,0,1,0,0.0,0.0,0.0,0.0,0.8,1.0,0.4,1.0,3.0
6289,1976-07-19,Afghanistan,Pakistan,1.0,0.0,1,0,0,0.0,0.0,0.0,1.0,0.8,1.0,0.6,3.0,3.2
6291,1976-07-24,Afghanistan,India,1.0,1.0,0,0,1,1.0,0.2,0.2,0.0,0.6,1.0,0.8,0.0,2.4
40882,1976-10-12,Afghanistan,Pakistan,0.0,1.0,0,1,0,0.0,0.2,0.2,0.0,0.4,1.0,0.8,1.0,2.2
6601,1977-07-24,Afghanistan,India,0.0,3.0,0,1,0,0.0,0.2,0.2,1.0,0.4,0.0,0.8,1.0,1.2
41487,1979-03-05,Afghanistan,Bangladesh,2.0,3.0,0,1,0,0.0,0.2,0.2,1.0,0.6,0.0,0.6,3.0,1.6
43094,1984-09-10,Afghanistan,Qatar,0.0,8.0,0,1,0,0.0,0.2,0.2,1.0,0.6,2.0,0.8,3.0,1.6
43095,1984-09-12,Afghanistan,China,0.0,6.0,0,1,0,0.0,0.0,0.0,1.0,0.8,0.0,0.6,8.0,3.2
43106,1984-09-15,Afghanistan,Hong Kong,0.0,0.0,0,0,1,0.0,0.0,0.0,1.0,1.0,0.0,0.4,6.0,4.2
43113,1984-09-20,Afghanistan,Jordan,1.0,6.0,0,1,0,0.0,0.0,0.0,0.0,0.8,0.0,0.4,0.0,4.0
52298,2003-03-16,Afghanistan,Kyrgyzstan,2.0,1.0,1,0,0,0.0,0.0,0.0,1.0,0.8,1.0,0.6,6.0,4.6
52301,2003-03-18,Afghanistan,Nepal,0.0,4.0,0,1,0,1.0,0.2,0.2,0.0,0.6,2.0,0.6,1.0,4.2
52923,2003-11-19,Afghanistan,Turkmenistan,0.0,11.0,0,1,0,0.0,0.2,0.2,1.0,0.6,0.0,0.6,4.0,3.4
18380,2003-11-23,Afghanistan,Turkmenistan,0.0,2.0,0,1,0,0.0,0.2,0.2,1.0,0.6,0.0,0.6,11.0,4.4
54409,2005-11-09,Afghanistan,Tajikistan,0.0,4.0,0,1,0,0.0,0.2,0.2,1.0,0.8,0.0,0.6,2.0,4.8
55630,2007-10-08,Afghanistan,Syria,0.0,3.0,0,1,0,0.0,0.2,0.2,1.0,0.8,0.0,0.4,4.0,4.4
21168,2007-10-26,Afghanistan,Syria,1.0,2.0,0,1,0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,3.0,4.8
58023,2010-11-17,Afghanistan,Tajikistan,0.0,1.0,0,1,0,0.0,0.0,0.0,1.0,1.0,1.0,0.2,2.0,4.4
23806,2011-06-29,Afghanistan,Palestine,0.0,2.0,0,1,0,0.0,0.0,0.0,1.0,1.0,0.0,0.2,1.0,2.4
58372,2011-07-03,Afghanistan,Palestine,1.0,1.0,0,0,1,0.0,0.0,0.0,1.0,1.0,0.0,0.2,2.0,2.4
59950,2013-06-04,Afghanistan,Tajikistan,2.0,3.0,0,1,0,0.0,0.0,0.0,0.0,0.8,1.0,0.4,1.0,1.8
25578,2013-08-20,Afghanistan,Pakistan,3.0,0.0,1,0,0,0.0,0.0,0.0,1.0,0.8,2.0,0.8,3.0,1.8
25960,2014-04-13,Afghanistan,Kyrgyzstan,0.0,0.0,0,0,1,1.0,0.2,0.2,0.0,0.6,3.0,1.2,0.0,1.4

In [17]:
matches_helper_combined.shape

(69098, 8)