In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pycountry

In [5]:
df = pd.read_csv("../data/raw/results.csv")

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49505 entries, 0 to 49504
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        49505 non-null  object
 1   home_team   49505 non-null  object
 2   away_team   49505 non-null  object
 3   home_score  49503 non-null  float64
 4   away_score  49503 non-null  float64
 5   tournament  49505 non-null  object
 6   city        49505 non-null  object
 7   country     49505 non-null  object
 8   neutral     49505 non-null  bool
dtypes: bool(1), float64(2), object(6)
memory usage: 3.1+ MB

In [7]:
df.describe()

         home_score    away_score
count  49503.000000  49503.000000
mean       1.757207      1.181908
std        1.773785      1.401637
min        0.000000      0.000000
25%        1.000000      0.000000
50%        1.000000      1.000000
75%        2.000000      2.000000
max       31.000000     21.000000

In [8]:
df.head(5)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [9]:
df.isnull().sum()

date          0
home_team     0
away_team     0
home_score    2
away_score    2
tournament    0
city          0
country       0
neutral       0
dtype: int64

In [10]:
(df == 0).sum()

date              0
home_team         0
away_team         0
home_score    11930
away_score    18475
tournament        0
city              0
country           0
neutral       36360
dtype: int64

In [11]:
df.duplicated().sum()
df[["home_team", "away_team", "date"]].duplicated().sum()

np.int64(2)

In [12]:
df[df.duplicated(subset=["home_team", "away_team", "date"], keep=False)]

#verified that multiple same day friendlies exist
#  tahiti vs new caledonia is a valid entry here

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
9641,1974-02-17,Tahiti,New Caledonia,2.0,1.0,Friendly,Papeete,Tahiti,False
9642,1974-02-17,Tahiti,New Caledonia,1.0,2.0,Friendly,Papeete,Tahiti,False
49352,2026-06-06,Gibraltar,Cayman Islands,4.0,1.0,Friendly,Gibraltar,Gibraltar,False
49361,2026-06-06,Gibraltar,Cayman Islands,4.0,1.0,Friendly,Europa Point,Gibraltar,False

In [13]:
cleaned_df = df.drop_duplicates(
    subset = [
        "date",
        "home_team",
        "away_team", 
        "home_score", 
        "away_score", 
        "tournament",
        "country",
        "neutral" 
    ]
)

In [14]:
cleaned_df["home_score"].value_counts().sort_index()

cleaned_df[cleaned_df["home_score"] >= 20 ]

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
6580,1966-04-03,Libya,Oman,21.0,0.0,Arab Cup,Baghdad,Iraq,True
8551,1971-09-13,Tahiti,Cook Islands,30.0,0.0,South Pacific Games,Papeete,Tahiti,False
11916,1979-08-30,Fiji,Kiribati,24.0,0.0,South Pacific Games,Nausori,Fiji,False
21957,1997-05-13,Kazakhstan,Guam,20.0,1.0,East Asian Games,Busan,South Korea,True
24181,2000-02-14,Kuwait,Bhutan,20.0,0.0,AFC Asian Cup qualification,Kuwait City,Kuwait,False
25422,2001-04-09,Australia,Tonga,22.0,0.0,FIFA World Cup qualification,Coffs Harbour,Australia,False
25425,2001-04-11,Australia,American Samoa,31.0,0.0,FIFA World Cup qualification,Coffs Harbour,Australia,False
30518,2006-11-24,Sápmi,Monaco,21.0,1.0,Viva World Cup,Hyères,France,True
37059,2013-06-23,Quebec,Tibet,21.0,0.0,"International Tournament of Peoples, Cultures ...",Marseille,France,True
37061,2013-06-24,Provence,Tibet,22.0,0.0,"International Tournament of Peoples, Cultures ...",Marseille,France,False

In [15]:
cleaned_df[cleaned_df["home_score"] >= 20 ]

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
6580,1966-04-03,Libya,Oman,21.0,0.0,Arab Cup,Baghdad,Iraq,True
8551,1971-09-13,Tahiti,Cook Islands,30.0,0.0,South Pacific Games,Papeete,Tahiti,False
11916,1979-08-30,Fiji,Kiribati,24.0,0.0,South Pacific Games,Nausori,Fiji,False
21957,1997-05-13,Kazakhstan,Guam,20.0,1.0,East Asian Games,Busan,South Korea,True
24181,2000-02-14,Kuwait,Bhutan,20.0,0.0,AFC Asian Cup qualification,Kuwait City,Kuwait,False
25422,2001-04-09,Australia,Tonga,22.0,0.0,FIFA World Cup qualification,Coffs Harbour,Australia,False
25425,2001-04-11,Australia,American Samoa,31.0,0.0,FIFA World Cup qualification,Coffs Harbour,Australia,False
30518,2006-11-24,Sápmi,Monaco,21.0,1.0,Viva World Cup,Hyères,France,True
37059,2013-06-23,Quebec,Tibet,21.0,0.0,"International Tournament of Peoples, Cultures ...",Marseille,France,True
37061,2013-06-24,Provence,Tibet,22.0,0.0,"International Tournament of Peoples, Cultures ...",Marseille,France,False

In [16]:
cleaned_df["tournament"].unique()

array(['Friendly', 'British Home Championship', 'Évence Coppée Trophy',
       'Muratti Vase', 'Copa Lipton', 'Copa Newton',
       'Copa Premio Honor Argentino', 'Olympic Games',
       'Copa Premio Honor Uruguayo', 'Far Eastern Championship Games',
       'Copa Roca', 'Copa América', 'Inter-Allied Games', 'Peace Cup',
       'Open International Championship', 'Soccer Ashes',
       'Copa Chevallier Boutell', 'Nordic Championship',
       'Central European International Cup', 'Baltic Cup', 'Balkan Cup',
       'Central American and Caribbean Games', 'FIFA World Cup',
       'Copa Rio Branco', 'FIFA World Cup qualification',
       'Bolivarian Games', 'CCCF Championship', 'NAFC Championship',
       'Copa Oswaldo Cruz', 'Asian Games', 'Pan American Championship',
       'Copa del Pacífico', "Copa Bernardo O'Higgins",
       'AFC Asian Cup qualification', 'Atlantic Cup', 'AFC Asian Cup',
       'African Cup of Nations', 'Copa Paz del Chaco',
       'Merdeka Tournament', 'UEFA Euro qualification',
       'Southeast Asian Peninsular Games', 'African Friendship Games',
       'UEFA Euro', 'Windward Islands Tournament',
       'African Cup of Nations qualification', 'Vietnam Independence Cup',
       'Copa Carlos Dittborn', 'Phillip Seaga Cup',
       'CONCACAF Championship', 'Copa Juan Pinto Durán', 'Arab Cup',
       'South Pacific Games', 'Zambian Independence Tournament',
       'CONCACAF Championship qualification', 'Copa Artigas',
       'All-African Games', 'GaNEFo', 'Copa América qualification',
       "King's Cup", 'Gulf Cup', 'Indonesia Tournament', 'Korea Cup',
       'Palestine Cup', 'Brazil Independence Cup', 'Copa Ramón Castilla',
       'Oceania Nations Cup', 'CECAFA Cup', 'Kuneitra Cup',
       'Copa Félix Bogado', 'Real Madrid 75th Anniversary Cup',
       'Beijing International Friendship Tournament',
       'Southeast Asian Games', 'Kirin Cup',
       'CFU Caribbean Cup qualification', 'CFU Caribbean Cup',
       'Amílcar Cabral Cup', 'FIFA 75th Anniversary Cup',
       'Indian Ocean Island Games',
       'Guangzhou International Friendship Tournament', 'Mundialito',
       'South Pacific Mini Games', 'West African Cup', 'Nehru Cup',
       'Merlion Cup', 'Trans-Tasman Cup', 'Great Wall Cup',
       'South Asian Games', 'UDEAC Cup', 'Rous Cup',
       'CONMEBOL–UEFA Cup of Champions', 'Miami Cup',
       'Lunar New Year Cup', 'Arab Cup qualification',
       'Tournoi de France', 'Malta International Tournament',
       'Four Nations Tournament', 'Matthews Cup',
       'Tournament Burkina Faso', 'Marlboro Cup', 'Melanesia Cup',
       'Island Games', 'NAFU Championship', 'Dynasty Cup',
       'Dakar Tournament', 'UNCAF Cup', 'Scania 100 Tournament',
       'Gold Cup', 'USA Cup', 'Jordan International Tournament',
       'Confederations Cup', 'East Asian Games',
       'United Arab Emirates Friendship Tournament', 'Joe Robbie Cup',
       'Oceania Nations Cup qualification', 'Simba Tournament',
       'SAFF Cup', 'AFF Championship', 'King Hassan II Tournament',
       'Cyprus International Tournament', 'Dunhill Cup',
       'COSAFA Cup qualification', 'COSAFA Cup', 'Gold Cup qualification',
       'AFF Championship qualification', 'SKN Football Festival',
       "Four Nations' Cup", 'UNIFFAC Cup', 'WAFF Championship',
       'Millennium Cup', 'Cup of Ancient Civilizations',
       "Prime Minister's Cup", 'Unity Cup', 'The Other Final',
       'EAFF Championship', 'TIFOCO Tournament', 'Afro-Asian Games',
       'AFC Challenge Cup', 'FIFI Wild Cup', 'ELF Cup', 'Viva World Cup',
       'AFC Challenge Cup qualification', "Coupe de l'Outre-Mer",
       'VFF Cup', 'Corsica Cup', 'Dragon Cup', 'ABCS Tournament',
       'Nile Basin Tournament', 'Nations Cup', 'Copa Confraternidad',
       'Pacific Games', 'Superclásico de las Américas',
       'Palestine International Championship', 'Philippine Peace Cup',
       'Kirin Challenge Cup',
       'International Tournament of Peoples, Cultures and Tribes',
       'Tynwald Hill Tournament', 'OSN Cup', 'CONIFA World Football Cup',
       'Niamh Challenge Cup', 'CONIFA European Football Cup',
       'Benedikt Fontana Cup', 'ConIFA Challenger Cup',
       'Hungary Heritage Cup', 'World Unity Cup', 'AFC Solidarity Cup',
       'Pacific Mini Games', 'Intercontinental Cup',
       'UEFA Nations League', 'CONCACAF Nations League qualification',
       'Atlantic Heritage Cup', 'Inter Games', 'CONCACAF Nations League',
       'CONIFA World Cup qualification', 'Three Nations Cup',
       'Mahinda Rajapaksa Cup', 'Navruz Cup',
       'CONIFA Africa Football Cup', 'CONIFA South America Football Cup',
       "MSG Prime Minister's Cup", 'Tri Nation Tournament',
       'CAFA Nations Cup', 'Mauritius Four Nations Cup',
       'CONIFA World Football Cup qualification', 'CONIFA Asia Cup',
       'FIFA Series', 'Marianas Cup', 'Tri-Nations Series',
       'ASEAN Championship qualification', 'ASEAN Championship',
       'EAFF Championship qualification', 'Mapinduzi Cup',
       'Canadian Shield', 'Outrigger Challenge Cup',
       'South Asian Super Cup', 'CONCACAF Series',
       'Al Ain International Cup', 'Morocco, Capital of African Football',
       'Mukuru 4 Nations',
       'Diamond Jubilee International Football Tournament',
       'Tri-Nations Cup'], dtype=object)

In [17]:
valid_tournaments = [
    "Friendly",
    "FIFA World Cup",
    "FIFA World Cup qualification", 
    "UEFA Euro", 
    "UEFA Euro qualification",
    "Copa América",
    "Copa América qualification",
    "African Cup of Nations", 
    "African Cup of Nations qualification", 
    "AFC Asian Cup",
    "AFC Asian Cup qualification",
    "Gold Cup", 
    "Gold Cup qualification", 
    "Oceania Nations Cup", 
    "Oceania Nations Cup qualification"
]

cleaned_df = df[df["tournament"].isin(valid_tournaments)]
cleaned_df["tournament"].unique()

array(['Friendly', 'Copa América', 'FIFA World Cup',
       'FIFA World Cup qualification', 'AFC Asian Cup qualification',
       'AFC Asian Cup', 'African Cup of Nations',
       'UEFA Euro qualification', 'UEFA Euro',
       'African Cup of Nations qualification',
       'Copa América qualification', 'Oceania Nations Cup', 'Gold Cup',
       'Oceania Nations Cup qualification', 'Gold Cup qualification'],
      dtype=object)

In [28]:
cleaned_df["home_team"].nunique()

282

In [27]:
cleaned_df["away_team"].nunique()

277

In [30]:
all_countries = pd.concat([cleaned_df["home_team"],
                           cleaned_df["away_team"]]).unique() 

sorted(all_countries)

['Abkhazia',
 'Afghanistan',
 'Albania',
 'Alderney',
 'Algeria',
 'Ambazonia',
 'American Samoa',
 'Andalusia',
 'Andorra',
 'Angola',
 'Anguilla',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Artsakh',
 'Aruba',
 'Asturias',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barawa',
 'Barbados',
 'Basque Country',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bolivia',
 'Bonaire',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'British Virgin Islands',
 'Brittany',
 'Brunei',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Canary Islands',
 'Cape Verde',
 'Cascadia',
 'Catalonia',
 'Cayman Islands',
 'Central African Republic',
 'Central Spain',
 'Chad',
 'Chagos Islands',
 'Chechnya',
 'Chile',
 'China',
 'Cilento',
 'Colombia',
 'Comoros',
 'Congo',
 'Cook Islands',
 'Corsica',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Curaçao',
 'Cyprus',
 'Czech Republic',
 'Czechoslovakia',
 'DR Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Donetsk PR',
 'East Turkestan',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Elba Island',
 'Ellan Vannin',
 'England',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Eswatini',
 'Ethiopia',
 'Faroe Islands',
 'Fiji',
 'Finland',
 'France',
 'Franconia',
 'French Guiana',
 'Gabon',
 'Galicia',
 'Gambia',
 'Georgia',
 'German DR',
 'Germany',
 'Ghana',
 'Gibraltar',
 'Gozo',
 'Greece',
 'Greenland',
 'Grenada',
 'Guadeloupe',
 'Guam',
 'Guatemala',
 'Guernsey',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hong Kong',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Israel',
 'Italy',
 'Ivory Coast',
 'Jamaica',
 'Japan',
 'Jersey',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kernow',
 'Kosovo',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luhansk PR',
 'Luxembourg',
 'Macau',
 'Madagascar',
 'Madrid',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Manchukuo',
 'Martinique',
 'Mauritania',
 'Mauritius',
 'Mayotte',
 'Mexico',
 'Micronesia',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Montserrat',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Netherlands',
 'New Caledonia',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Korea',
 'North Macedonia',
 'North Vietnam',
 'Northern Cyprus',
 'Northern Ireland',
 'Northern Mariana Islands',
 'Norway',
 'Occitania',
 'Oman',
 'Padania',
 'Pakistan',
 'Palau',
 'Palestine',
 'Panama',
 'Panjab',
 'Papua New Guinea',
 'Paraguay',
 'Parishes of Jersey',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Provence',
 'Puerto Rico',
 'Qatar',
 'Raetia',
 'Republic of Ireland',
 'Romani people',
 'Romania',
 'Russia',
 'Rwanda',
 'Ryūkyū',
 'Réunion',
 'Saarland',
 'Saint Barthélemy',
 'Saint Helena',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Martin',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'San Marino',
 'Saudi Arabia',
 'Saugeais',
 'Scotland',
 'Sealand',
 'Seborga',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Silesia',
 'Singapore',
 'Sint Maarten',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'Somaliland',
 'South Africa',
 'South Korea',
 'South Ossetia',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Surrey',
 'Sweden',
 'Switzerland',
 'Syria',
 'Székely Land',
 'Sápmi',
 'São Tomé and Príncipe',
 'Tahiti',
 'Taiwan',
 'Tajikistan',
 'Tamil Eelam',
 'Tanzania',
 'Thailand',
 'Tibet',
 'Ticino',
 'Timor-Leste',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Turks and Caicos Islands',
 'Tuvalu',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Koreans in Japan',
 'United States',
 'United States Virgin Islands',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Vatican City',
 'Venezuela',
 'Vietnam',
 'Vietnam Republic',
 'Wales',
 'West Papua',
 'Western Sahara',
 'Yemen',
 'Yemen DPR',
 'Ynys Môn',
 'Yorkshire',
 'Yugoslavia',
 'Zambia',
 'Zanzibar',
 'Zimbabwe',
 'Åland Islands']

In [56]:
print(len(all_countries))

293

In [31]:
cleaned_df[
    (cleaned_df["home_team"] == "Abkhazia") |
    (cleaned_df["away_team"] == "Abkhazia")
]

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
36260,2012-09-25,Abkhazia,Artsakh,1.0,1.0,Friendly,Sukhumi,Georgia,False
36404,2012-10-21,Artsakh,Abkhazia,3.0,0.0,Friendly,Stepanakert,Azerbaijan,False
37317,2013-09-23,Abkhazia,South Ossetia,3.0,0.0,Friendly,Sukhumi,Georgia,False
38642,2015-05-05,Abkhazia,Luhansk PR,1.0,0.0,Friendly,Sukhumi,Georgia,False
38650,2015-05-14,Abkhazia,Donetsk PR,1.0,0.0,Friendly,Sukhumi,Georgia,False
39659,2016-05-21,Abkhazia,Donetsk PR,0.0,0.0,Friendly,Sukhumi,Georgia,False
40911,2017-08-31,Abkhazia,Donetsk PR,1.0,2.0,Friendly,Sukhumi,Georgia,False

In [32]:
fifa_df = pd.read_csv("../data/external/fifa-member-associations.csv")

In [33]:
fifa_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211 entries, 0 to 210
Data columns (total 9 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country.Iso3166.Alpha2Code     210 non-null    object
 1   Country.Name                   211 non-null    object
 2   Subdivision.Iso3166.Code       4 non-null      object
 3   FIFA.Code                      211 non-null    object
 4   FIFA.MemberAssociation         211 non-null    object
 5   FIFA.Joined                    211 non-null    int64
 6   Established                    211 non-null    int64
 7   ContinentalConfederation.Code  211 non-null    object
 8   ContinentalConfederation.Name  211 non-null    object
dtypes: int64(2), object(7)
memory usage: 15.0+ KB

In [34]:
fifa_df.head(5)

,Country.Iso3166.Alpha2Code,Country.Name,Subdivision.Iso3166.Code,FIFA.Code,FIFA.MemberAssociation,FIFA.Joined,Established,ContinentalConfederation.Code,ContinentalConfederation.Name
0,AD,Andorra,NaN,AND,Federació Andorrana de Futbol (FAF),1996,1994,UEFA,Union of European Football Associations (UEFA)
1,AE,United Arab Emirates (the),NaN,UAE,United Arab Emirates Football Association (UAEFA),1972,1971,AFC,Asian Football Confederation (AFC)
2,AF,Afghanistan,NaN,AFG,Afghanistan Football Federation (AFF),1948,1922,AFC,Asian Football Confederation (AFC)
3,AG,Antigua and Barbuda,NaN,ATG,Antigua and Barbuda Football Association (AFA),1970,1928,CONCACAF,"Confederation of North, Central America and Ca..."
4,AI,Anguilla,NaN,AIA,Anguilla Football Association (AFA),1996,1996,CONCACAF,"Confederation of North, Central America and Ca..."

In [37]:
fifa_df = fifa_df.drop(columns = ["Established", "Subdivision.Iso3166.Code"])

In [40]:

fifa_df = fifa_df.rename(columns={"Country.Name": "country_name", "FIFA.Code": "fifa_code", "FIFA.MemberAssociation": "fifa_member_association", "FIFA.Joined": "fifa_joined_year", "ContinentalConfederation.Code": "continental_confederation_code", "ContinentalConfederation.Name": "continental_confederation_name", "Country.Iso3166.Alpha2Code": "country_iso2_code"})

In [44]:
fifa_df.isnull().sum()
fifa_df[fifa_df["country_iso2_code"].isnull()]
fifa_df["country_iso2_code"] = fifa_df["country_iso2_code"].fillna("NA")

# iso 2 code for namibia is NA, NA here does NOT represent N/A!!

In [45]:
(fifa_df == 0).sum()

country_iso2_code                 0
country_name                      0
fifa_code                         0
fifa_member_association           0
fifa_joined_year                  0
continental_confederation_code    0
continental_confederation_name    0
dtype: int64

In [46]:
fifa_df.duplicated().sum()

np.int64(0)

In [ ]:
fifa_df["country_name"].duplicated().sum()  ## only flagged as it refers to the countries that make up the UK

np.int64(3)

In [48]:
fifa_df[fifa_df["country_name"].duplicated(keep=False)]

,country_iso2_code,country_name,fifa_code,fifa_member_association,fifa_joined_year,continental_confederation_code,continental_confederation_name
66,GB,United Kingdom of Great Britain and Northern I...,ENG,The Football Association (FA),1905,UEFA,Union of European Football Associations (UEFA)
67,GB,United Kingdom of Great Britain and Northern I...,NIR,Irish Football Association (IFA),1911,UEFA,Union of European Football Associations (UEFA)
68,GB,United Kingdom of Great Britain and Northern I...,SCO,Scottish Football Association (SFA),1910,UEFA,Union of European Football Associations (UEFA)
69,GB,United Kingdom of Great Britain and Northern I...,WAL,Football Association of Wales (FAW),1910,UEFA,Union of European Football Associations (UEFA)

In [49]:
fifa_df["fifa_member_association"].duplicated().sum()

np.int64(0)

In [51]:
fifa_df["continental_confederation_code"].unique()

array(['UEFA', 'AFC', 'CONCACAF', 'CAF', 'CONMEBOL', 'OFC'], dtype=object)

In [52]:
fifa_df["continental_confederation_name"].unique()

array(['Union of European Football Associations (UEFA)',
       'Asian Football Confederation (AFC)',
       'Confederation of North, Central America and Caribbean Association Football (CONCACAF)',
       'Confédération Africaine de Football (CAF)',
       'Confederação Sul-Americana de Futebol (CONMEBOL)',
       'Oceania Football Confederation (OCF)'], dtype=object)

In [54]:
fifa_df.head(30)

,country_iso2_code,country_name,fifa_code,fifa_member_association,fifa_joined_year,continental_confederation_code,continental_confederation_name
0,AD,Andorra,AND,Federació Andorrana de Futbol (FAF),1996,UEFA,Union of European Football Associations (UEFA)
1,AE,United Arab Emirates (the),UAE,United Arab Emirates Football Association (UAEFA),1972,AFC,Asian Football Confederation (AFC)
2,AF,Afghanistan,AFG,Afghanistan Football Federation (AFF),1948,AFC,Asian Football Confederation (AFC)
3,AG,Antigua and Barbuda,ATG,Antigua and Barbuda Football Association (AFA),1970,CONCACAF,"Confederation of North, Central America and Ca..."
4,AI,Anguilla,AIA,Anguilla Football Association (AFA),1996,CONCACAF,"Confederation of North, Central America and Ca..."
5,AL,Albania,ALB,Federata Shqiptare e Futbollit (FSHF),1930,UEFA,Union of European Football Associations (UEFA)
6,AM,Armenia,ARM,Hajastani futboli federazia (HFF),1992,UEFA,Union of European Football Associations (UEFA)
7,AO,Angola,ANG,Federação Angolana de Futebol (FAF),1980,CAF,Confédération Africaine de Football (CAF)
8,AR,Argentina,ARG,Asociación del Fútbol Argentino (AFA),1912,CONMEBOL,Confederação Sul-Americana de Futebol (CONMEBOL)
9,AS,American Samoa,ASA,Football Federation American Samoa (FFAS),1998,OFC,Oceania Football Confederation (OCF)
10,AT,Austria,AUT,Österreichischer Fußball-Bund (ÖFB),1905,UEFA,Union of European Football Associations (UEFA)
11,AU,Australia,AUS,Football Federation Australia (FFA),1963,AFC,Asian Football Confederation (AFC)
12,AW,Aruba,ARU,Arubaanse Voetbal Bond (AVB),1988,CONCACAF,"Confederation of North, Central America and Ca..."
13,AZ,Azerbaijan,AZE,Azərbaycan Futbol Federasiyaları Assosiasiyası...,1994,UEFA,Union of European Football Associations (UEFA)
14,BA,Bosnia and Herzegovina,BIH,Nogometni/Fudbalski Savez Bosne i Hercegovine ...,1996,UEFA,Union of European Football Associations (UEFA)
15,BB,Barbados,BRB,Barbados Football Association (BFA),1968,CONCACAF,"Confederation of North, Central America and Ca..."
16,BD,Bangladesh,BAN,Bangladesh Football Federation (BFF),1974,AFC,Asian Football Confederation (AFC)
17,BE,Belgium,BEL,Koninklijke Belgische Voetbalbond (KBFV),1904,UEFA,Union of European Football Associations (UEFA)
18,BF,Burkina Faso,BFA,Fédération Burkinabè de Football (FBF),1964,CAF,Confédération Africaine de Football (CAF)
19,BG,Bulgaria,BUL,Bulgarski futbolen Sojus (BFS),1924,UEFA,Union of European Football Associations (UEFA)
20,BH,Bahrain,BHR,Bahrain Football Association (BFA),1966,AFC,Asian Football Confederation (AFC)
21,BI,Burundi,BDI,Fédération de Football du Burundi (FFB),1972,CAF,Confédération Africaine de Football (CAF)
22,BJ,Benin,BEN,Fédération Béninoise de Football (FBF),1969,CAF,Confédération Africaine de Football (CAF)
23,BM,Bermuda,BER,Bermuda Football Association (BFA),1962,CONCACAF,"Confederation of North, Central America and Ca..."
24,BN,Brunei Darussalam,BRU,National Football Association of Brunei Daruss...,1969,AFC,Asian Football Confederation (AFC)
25,BO,Bolivia (Plurinational State of),BOL,Federación Boliviana de Fútbol (FBF),1926,CONMEBOL,Confederação Sul-Americana de Futebol (CONMEBOL)
26,BR,Brazil,BRA,Confederação Brasileira de Futebol (CBF),1917,CONMEBOL,Confederação Sul-Americana de Futebol (CONMEBOL)
27,BS,Bahamas (the),BAH,Bahamas Football Association (BFA),1968,CONCACAF,"Confederation of North, Central America and Ca..."
28,BT,Bhutan,BHU,Bhutan Football Federation (BFF),2000,AFC,Asian Football Confederation (AFC)
29,BW,Botswana,BOT,Botswana Football Association (BFA),1976,CAF,Confédération Africaine de Football (CAF)

In [57]:
cleaned_df.head(10)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False
5,1876-03-25,Scotland,Wales,4.0,0.0,Friendly,Glasgow,Scotland,False
6,1877-03-03,England,Scotland,1.0,3.0,Friendly,London,England,False
7,1877-03-05,Wales,Scotland,0.0,2.0,Friendly,Wrexham,Wales,False
8,1878-03-02,Scotland,England,7.0,2.0,Friendly,Glasgow,Scotland,False
9,1878-03-23,Scotland,Wales,9.0,0.0,Friendly,Glasgow,Scotland,False

In [ ]:
only_all_countries = set(all_countries) - set(fifa_df["country_name"])



print(only_all_countries)

{'Syria', 'England', 'Luhansk PR', 'Scotland', 'French Guiana', 'Réunion', 'Turkey', 'Brittany', 'Cayman Islands', 'Asturias', 'Northern Cyprus', 'Székely Land', 'Cascadia', 'Padania', 'Abkhazia', 'Saint Helena', 'Andalusia', 'Taiwan', 'Basque Country', 'Sealand', 'Chagos Islands', 'Ivory Coast', 'Sint Maarten', 'Sudan', 'Romani people', 'Faroe Islands', 'Sápmi', 'Guernsey', 'Artsakh', 'Cilento', 'United Koreans in Japan', 'Republic of Ireland', 'Western Sahara', 'Jersey', 'Palestine', 'East Turkestan', 'Dominican Republic', 'Niger', 'Vietnam', 'Silesia', 'Åland Islands', 'North Vietnam', 'Turks and Caicos Islands', 'Kosovo', 'Philippines', 'Laos', 'Panjab', 'Tanzania', 'United States', 'Mauritania', 'Saint Barthélemy', 'DR Congo', 'Gambia', 'Donetsk PR', 'Russia', 'Barawa', 'North Korea', 'Ynys Môn', 'Elba Island', 'South Korea', 'Chechnya', 'United States Virgin Islands', 'Kernow', 'Alderney', 'Somaliland', 'Occitania', 'Tahiti', 'Papua New Guinea', 'Cook Islands', 'Raetia', 'Tamil Eelam', 'Iran', 'West Papua', 'Bonaire', 'Yorkshire', 'Monaco', 'Greenland', 'Ellan Vannin', 'Comoros', 'Central Spain', 'Venezuela', 'Cape Verde', 'Saint Martin', 'Macau', 'Czechoslovakia', 'Vietnam Republic', 'Tibet', 'Vatican City', 'Czech Republic', 'Canary Islands', 'Provence', 'Tuvalu', 'Bolivia', 'Central African Republic', 'South Ossetia', 'Bahamas', 'Zanzibar', 'Moldova', 'Ryūkyū', 'Madrid', 'German DR', 'Surrey', 'Franconia', 'Saarland', 'Micronesia', 'Galicia', 'United Arab Emirates', 'Saugeais', 'Guadeloupe', 'Wales', 'Ticino', 'Ambazonia', 'British Virgin Islands', 'Netherlands', 'Manchukuo', 'Congo', 'São Tomé and Príncipe', 'Parishes of Jersey', 'Seborga', 'Catalonia', 'Brunei', 'Northern Mariana Islands', 'Yemen DPR', 'Northern Ireland', 'Yugoslavia', 'Corsica', 'Gozo'}

In [61]:
fifa_df["country_name"].unique()

array(['Andorra', 'United Arab Emirates (the)', 'Afghanistan',
       'Antigua and Barbuda', 'Anguilla', 'Albania', 'Armenia', 'Angola',
       'Argentina', 'American Samoa', 'Austria', 'Australia', 'Aruba',
       'Azerbaijan', 'Bosnia and Herzegovina', 'Barbados', 'Bangladesh',
       'Belgium', 'Burkina Faso', 'Bulgaria', 'Bahrain', 'Burundi',
       'Benin', 'Bermuda', 'Brunei Darussalam',
       'Bolivia (Plurinational State of)', 'Brazil', 'Bahamas (the)',
       'Bhutan', 'Botswana', 'Belarus', 'Belize', 'Canada',
       'Congo (the Democratic Republic of the)',
       'Central African Republic (the)', 'Congo (the)', 'Switzerland',
       "Côte d'Ivoire", 'Cook Islands (the)', 'Chile', 'Cameroon',
       'China', 'Colombia', 'Costa Rica', 'Cuba', 'Cabo Verde', 'Curaçao',
       'Cyprus', 'Czechia', 'Germany', 'Djibouti', 'Denmark', 'Dominica',
       'Dominican Republic (the)', 'Algeria', 'Ecuador', 'Estonia',
       'Egypt', 'Eritrea', 'Spain', 'Ethiopia', 'Finland', 'Fiji',
       'Micronesia (Federated States of)', 'France', 'Gabon',
       'United Kingdom of Great Britain and Northern Ireland (the)',
       'Grenada', 'Georgia', 'Ghana', 'Gibraltar', 'Gambia (the)',
       'Guinea', 'Equatorial Guinea', 'Greece', 'Guatemala', 'Guam',
       'Guinea-Bissau', 'Guyana', 'Hong Kong', 'Honduras', 'Croatia',
       'Haiti', 'Hungary', 'Indonesia', 'Ireland', 'Israel', 'India',
       'Iraq', 'Iran (Islamic Republic of)', 'Iceland', 'Italy',
       'Jamaica', 'Jordan', 'Japan', 'Kenya', 'Kyrgyzstan', 'Cambodia',
       'Comoros (the)', 'Saint Kitts and Nevis',
       "Korea (the Democratic People's Republic of)",
       'Korea (the Republic of)', 'Kuwait', 'Cayman Islands (the)',
       'Kazakhstan', "Lao People's Democratic Republic (the)", 'Lebanon',
       'Saint Lucia', 'Liechtenstein', 'Sri Lanka', 'Liberia', 'Lesotho',
       'Lithuania', 'Luxembourg', 'Latvia', 'Libya', 'Morocco',
       'Moldova (the Republic of)', 'Montenegro', 'Madagascar',
       'North Macedonia', 'Mali', 'Myanmar', 'Mongolia', 'Macao',
       'Martinique', 'Montserrat', 'Malta', 'Mauritius', 'Maldives',
       'Malawi', 'Mexico', 'Malaysia', 'Mozambique', 'Namibia',
       'New Caledonia', 'Niger (the)', 'Nigeria', 'Nicaragua',
       'Netherlands (Kingdom of the)', 'Norway', 'Nepal', 'New Zealand',
       'Oman', 'Panama', 'Peru', 'French Polynesia', 'Philippines (the)',
       'Pakistan', 'Poland', 'Puerto Rico', 'Palestine, State of',
       'Portugal', 'Palau', 'Paraguay', 'Qatar', 'Romania', 'Serbia',
       'Russian Federation (the)', 'Rwanda', 'Saudi Arabia',
       'Solomon Islands', 'Seychelles', 'Sudan (the)', 'Sweden',
       'Singapore', 'Slovenia', 'Slovakia', 'Sierra Leone', 'San Marino',
       'Senegal', 'Somalia', 'Suriname', 'South Sudan',
       'Sao Tome and Principe', 'El Salvador',
       'Syrian Arab Republic (the)', 'Eswatini',
       'Turks and Caicos Islands (the)', 'Chad', 'Togo', 'Thailand',
       'Tajikistan', 'Timor-Leste', 'Turkmenistan', 'Tunisia', 'Tonga',
       'Türkiye', 'Trinidad and Tobago', 'Taiwan (Province of China)',
       'Tanzania, the United Republic of', 'Ukraine', 'Uganda',
       'United States of America (the)', 'Uruguay', 'Uzbekistan',
       'Saint Vincent and the Grenadines',
       'Venezuela (Bolivarian Republic of)', 'Virgin Islands (British)',
       'Virgin Islands (U.S.)', 'Viet Nam', 'Vanuatu', 'Samoa', 'Yemen',
       'Mayotte', 'South Africa', 'Zambia', 'Zimbabwe'], dtype=object)