In [29]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [30]:
df = pd.read_csv("../data/raw/goalscorers.csv")

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47903 entries, 0 to 47902
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       47903 non-null  object
 1   home_team  47903 non-null  object
 2   away_team  47903 non-null  object
 3   team       47903 non-null  object
 4   scorer     47859 non-null  object
 5   minute     47649 non-null  float64
 6   own_goal   47903 non-null  bool
 7   penalty    47903 non-null  bool
dtypes: bool(2), float64(1), object(5)
memory usage: 2.3+ MB

In [32]:
df.head(5)

,date,home_team,away_team,team,scorer,minute,own_goal,penalty
0,1916-07-02,Chile,Uruguay,Uruguay,José Piendibene,44.0,False,False
1,1916-07-02,Chile,Uruguay,Uruguay,Isabelino Gradín,55.0,False,False
2,1916-07-02,Chile,Uruguay,Uruguay,Isabelino Gradín,70.0,False,False
3,1916-07-02,Chile,Uruguay,Uruguay,José Piendibene,75.0,False,False
4,1916-07-06,Argentina,Chile,Argentina,Alberto Ohaco,2.0,False,False

In [33]:
df.tail(5)

,date,home_team,away_team,team,scorer,minute,own_goal,penalty
47898,2026-07-14,France,Spain,Spain,Mikel Oyarzabal,22.0,False,True
47899,2026-07-14,France,Spain,Spain,Pedro Porro,58.0,False,False
47900,2026-07-15,England,Argentina,England,Anthony Gordon,55.0,False,False
47901,2026-07-15,England,Argentina,Argentina,Enzo Fernández,85.0,False,False
47902,2026-07-15,England,Argentina,Argentina,Lautaro Martínez,90.0,False,False

In [34]:
df.isnull().sum()

date           0
home_team      0
away_team      0
team           0
scorer        44
minute       254
own_goal       0
penalty        0
dtype: int64

In [35]:
df = df.dropna()

In [36]:
(df == 0).sum()

date             0
home_team        0
away_team        0
team             0
scorer           0
minute           0
own_goal     46713
penalty      44386
dtype: int64

In [37]:
df["date"] = pd.to_datetime(df["date"])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 47649 entries, 0 to 47902
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       47649 non-null  datetime64[ns]
 1   home_team  47649 non-null  object
 2   away_team  47649 non-null  object
 3   team       47649 non-null  object
 4   scorer     47649 non-null  object
 5   minute     47649 non-null  float64
 6   own_goal   47649 non-null  bool
 7   penalty    47649 non-null  bool
dtypes: bool(2), datetime64[ns](1), float64(1), object(4)
memory usage: 2.6+ MB

In [38]:
df.duplicated().sum()

np.int64(10)

In [39]:
df[df.duplicated(keep=False)].sort_values(list(df.columns))

,date,home_team,away_team,team,scorer,minute,own_goal,penalty
9344,1981-06-06,Fiji,Taiwan,Fiji,Ratu Jone,55.0,False,False
9345,1981-06-06,Fiji,Taiwan,Fiji,Ratu Jone,55.0,False,False
21014,2001-04-30,Oman,Laos,Oman,Hani Al-Dhabit,45.0,False,False
21015,2001-04-30,Oman,Laos,Oman,Hani Al-Dhabit,45.0,False,False
22148,2002-01-30,Burkina Faso,Ghana,Ghana,Isaac Boakye,90.0,False,False
22149,2002-01-30,Burkina Faso,Ghana,Ghana,Isaac Boakye,90.0,False,False
23267,2003-12-03,Maldives,Mongolia,Maldives,Ibrahim Fazeel,45.0,False,False
23268,2003-12-03,Maldives,Mongolia,Maldives,Ibrahim Fazeel,45.0,False,False
24630,2004-10-09,Turkey,Kazakhstan,Turkey,Fatih Tekke,90.0,False,False
24631,2004-10-09,Turkey,Kazakhstan,Turkey,Fatih Tekke,90.0,False,False
34442,2015-06-13,Poland,Georgia,Poland,Robert Lewandowski,90.0,False,False
34443,2015-06-13,Poland,Georgia,Poland,Robert Lewandowski,90.0,False,False
38965,2019-09-08,Spain,Faroe Islands,Spain,Paco Alcácer,90.0,False,False
38966,2019-09-08,Spain,Faroe Islands,Spain,Paco Alcácer,90.0,False,False
41301,2021-09-05,San Marino,Poland,Poland,Adam Buksa,90.0,False,False
41302,2021-09-05,San Marino,Poland,Poland,Adam Buksa,90.0,False,False
41775,2021-10-12,Syria,Lebanon,Lebanon,Mohamad Kdouh,45.0,False,False
41776,2021-10-12,Syria,Lebanon,Lebanon,Mohamad Kdouh,45.0,False,False
42832,2022-09-25,Moldova,Liechtenstein,Moldova,Victor Stînă,90.0,False,False
42833,2022-09-25,Moldova,Liechtenstein,Moldova,Victor Stînă,90.0,False,False

In [40]:
df = df.drop_duplicates() 
df.duplicated().sum()

np.int64(0)

In [41]:
sorted(df["team"].unique())

['Afghanistan',
 'Albania',
 'Algeria',
 'American Samoa',
 'Andorra',
 'Angola',
 'Anguilla',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Aruba',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'British Virgin Islands',
 'Brunei',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Cayman Islands',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo',
 'Cook Islands',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Curaçao',
 'Cyprus',
 'Czech Republic',
 'Czechoslovakia',
 'DR Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'England',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Eswatini',
 'Ethiopia',
 'Faroe Islands',
 'Fiji',
 'Finland',
 'France',
 'French Guiana',
 'Gabon',
 'Gambia',
 'Georgia',
 'German DR',
 'Germany',
 'Ghana',
 'Gibraltar',
 'Greece',
 'Grenada',
 'Guadeloupe',
 'Guam',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hong Kong',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Israel',
 'Italy',
 'Ivory Coast',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kosovo',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Macau',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Martinique',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Moldova',
 'Mongolia',
 'Montenegro',
 'Montserrat',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Netherlands',
 'New Caledonia',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Korea',
 'North Macedonia',
 'Northern Ireland',
 'Norway',
 'Oman',
 'Pakistan',
 'Palestine',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Republic of Ireland',
 'Romania',
 'Russia',
 'Rwanda',
 'Saarland',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'San Marino',
 'Saudi Arabia',
 'Scotland',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Korea',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Sweden',
 'Switzerland',
 'Syria',
 'São Tomé and Príncipe',
 'Tahiti',
 'Taiwan',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Timor-Leste',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Turks and Caicos Islands',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United States',
 'United States Virgin Islands',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela',
 'Vietnam',
 'Vietnam Republic',
 'Wales',
 'Yemen',
 'Yemen DPR',
 'Yugoslavia',
 'Zambia',
 'Zimbabwe']

In [42]:
df["team"].nunique()

220

In [43]:
times = df["minute"].sort_values().unique() 
times

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
       111., 112., 113., 114., 115., 116., 117., 118., 119., 120., 122.])

In [44]:
df["own_goal"].value_counts()

own_goal
False    46703
True       936
Name: count, dtype: int64

In [45]:
df["penalty"].value_counts()

penalty
False    44376
True      3263
Name: count, dtype: int64

In [46]:
remove_nonFIFA_teams = ["Comoros", "Czechoslovakia", "Faroe Islands", "French Guiana", "German DR", "Guadeloupe", 
                           "Kosovo", "Macau", "Martinique", "Papua New Guinea", "Saarland", "Tahiti", 
                           "Vietnam Republic", "Yemen DPR", "Yugoslavia"]

df = df[~df["team"].isin(remove_nonFIFA_teams)]
df = df[~df["home_team"].isin(remove_nonFIFA_teams) & ~df["away_team"].isin(remove_nonFIFA_teams)]

In [47]:
df.tail(20)

,date,home_team,away_team,team,scorer,minute,own_goal,penalty
47883,2026-07-07,Argentina,Egypt,Argentina,Cristian Romero,79.0,False,False
47884,2026-07-07,Argentina,Egypt,Argentina,Lionel Messi,83.0,False,False
47885,2026-07-07,Argentina,Egypt,Argentina,Enzo Fernández,90.0,False,False
47886,2026-07-09,France,Morocco,France,Kylian Mbappé,60.0,False,False
47887,2026-07-09,France,Morocco,France,Ousmane Dembélé,66.0,False,False
47888,2026-07-10,Spain,Belgium,Spain,Fabián Ruiz,30.0,False,False
47889,2026-07-10,Spain,Belgium,Belgium,Charles De Ketelaere,41.0,False,False
47890,2026-07-10,Spain,Belgium,Spain,Mikel Merino,88.0,False,False
47891,2026-07-11,Argentina,Switzerland,Argentina,Alexis Mac Allister,10.0,False,False
47892,2026-07-11,Argentina,Switzerland,Switzerland,Dan Ndoye,67.0,False,False
47893,2026-07-11,Argentina,Switzerland,Argentina,Julián Alvarez,112.0,False,False
47894,2026-07-11,Argentina,Switzerland,Argentina,Lautaro Martínez,120.0,False,False
47895,2026-07-11,Norway,England,Norway,Andreas Schjelderup,36.0,False,False
47896,2026-07-11,Norway,England,England,Jude Bellingham,45.0,False,False
47897,2026-07-11,Norway,England,England,Jude Bellingham,93.0,False,False
47898,2026-07-14,France,Spain,Spain,Mikel Oyarzabal,22.0,False,True
47899,2026-07-14,France,Spain,Spain,Pedro Porro,58.0,False,False
47900,2026-07-15,England,Argentina,England,Anthony Gordon,55.0,False,False
47901,2026-07-15,England,Argentina,Argentina,Enzo Fernández,85.0,False,False
47902,2026-07-15,England,Argentina,Argentina,Lautaro Martínez,90.0,False,False

In [48]:
new_data_eng = pd.DataFrame({
    'date': pd.to_datetime('2026-07-18'), 
    'home_team': 'France',                
    'away_team': 'England',               
    'team': 'England',                    
    'scorer': ['Declan Rice', 'Ezri Konsa', 'Bukayo Saka', 'Bukayo Saka', 'Bukayo Saka', 'Jude Bellingham'], 
    'minute': [3, 18, 37, 46, 87, 98], 
    'own_goal': [False, False, False, False, False, False], 
    'penalty': [False, False, False, False, True, False]
})

new_data_fr = pd.DataFrame({
    'date': pd.to_datetime('2026-07-18'), 
    'home_team': 'France',                
    'away_team': 'England',               
    'team': 'France',                    
    'scorer': ['Kylian Mbappé', 'Kylian Mbappé', 'Bradley Barcola', 'Ousmane Dembélé'], 
    'minute': [48, 66, 54, 96],
    'own_goal': [False, False, False, False], 
    'penalty': [False, False, False, False]
})


wc_data = pd.DataFrame({
    'date': pd.to_datetime('2026-07-19'), 
    'home_team': 'Spain',                
    'away_team': 'Argentina',               
    'team': 'Spain',                    
    'scorer': 'Ferran Torres', 
    'minute': 106, 
    'own_goal': [False], 
    'penalty': [False]
})

df = pd.concat([df, new_data_eng], ignore_index = True)
df = pd.concat([df, new_data_fr], ignore_index = True)
df = pd.concat([df, wc_data], ignore_index = True)

In [49]:
df.tail(30)

,date,home_team,away_team,team,scorer,minute,own_goal,penalty
44745,2026-07-07,Argentina,Egypt,Argentina,Lionel Messi,83.0,False,False
44746,2026-07-07,Argentina,Egypt,Argentina,Enzo Fernández,90.0,False,False
44747,2026-07-09,France,Morocco,France,Kylian Mbappé,60.0,False,False
44748,2026-07-09,France,Morocco,France,Ousmane Dembélé,66.0,False,False
44749,2026-07-10,Spain,Belgium,Spain,Fabián Ruiz,30.0,False,False
44750,2026-07-10,Spain,Belgium,Belgium,Charles De Ketelaere,41.0,False,False
44751,2026-07-10,Spain,Belgium,Spain,Mikel Merino,88.0,False,False
44752,2026-07-11,Argentina,Switzerland,Argentina,Alexis Mac Allister,10.0,False,False
44753,2026-07-11,Argentina,Switzerland,Switzerland,Dan Ndoye,67.0,False,False
44754,2026-07-11,Argentina,Switzerland,Argentina,Julián Alvarez,112.0,False,False
44755,2026-07-11,Argentina,Switzerland,Argentina,Lautaro Martínez,120.0,False,False
44756,2026-07-11,Norway,England,Norway,Andreas Schjelderup,36.0,False,False
44757,2026-07-11,Norway,England,England,Jude Bellingham,45.0,False,False
44758,2026-07-11,Norway,England,England,Jude Bellingham,93.0,False,False
44759,2026-07-14,France,Spain,Spain,Mikel Oyarzabal,22.0,False,True
44760,2026-07-14,France,Spain,Spain,Pedro Porro,58.0,False,False
44761,2026-07-15,England,Argentina,England,Anthony Gordon,55.0,False,False
44762,2026-07-15,England,Argentina,Argentina,Enzo Fernández,85.0,False,False
44763,2026-07-15,England,Argentina,Argentina,Lautaro Martínez,90.0,False,False
44764,2026-07-18,France,England,England,Declan Rice,3.0,False,False
44765,2026-07-18,France,England,England,Ezri Konsa,18.0,False,False
44766,2026-07-18,France,England,England,Bukayo Saka,37.0,False,False
44767,2026-07-18,France,England,England,Bukayo Saka,46.0,False,False
44768,2026-07-18,France,England,England,Bukayo Saka,87.0,False,True
44769,2026-07-18,France,England,England,Jude Bellingham,98.0,False,False
44770,2026-07-18,France,England,France,Kylian Mbappé,48.0,False,False
44771,2026-07-18,France,England,France,Kylian Mbappé,66.0,False,False
44772,2026-07-18,France,England,France,Bradley Barcola,54.0,False,False
44773,2026-07-18,France,England,France,Ousmane Dembélé,96.0,False,False
44774,2026-07-19,Spain,Argentina,Spain,Ferran Torres,106.0,False,False

In [50]:
df.to_csv(
    "../data/cleaned/goal_scorers_clean.csv",
    index = False
)####