In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("../data/raw/goalscorers.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47891 entries, 0 to 47890
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       47891 non-null  object
 1   home_team  47891 non-null  object
 2   away_team  47891 non-null  object
 3   team       47891 non-null  object
 4   scorer     47847 non-null  object
 5   minute     47637 non-null  float64
 6   own_goal   47891 non-null  bool
 7   penalty    47891 non-null  bool
dtypes: bool(2), float64(1), object(5)
memory usage: 2.3+ MB

In [4]:
df.head(5)

,date,home_team,away_team,team,scorer,minute,own_goal,penalty
0,1916-07-02,Chile,Uruguay,Uruguay,José Piendibene,44.0,False,False
1,1916-07-02,Chile,Uruguay,Uruguay,Isabelino Gradín,55.0,False,False
2,1916-07-02,Chile,Uruguay,Uruguay,Isabelino Gradín,70.0,False,False
3,1916-07-02,Chile,Uruguay,Uruguay,José Piendibene,75.0,False,False
4,1916-07-06,Argentina,Chile,Argentina,Alberto Ohaco,2.0,False,False

In [28]:
df.tail(5)

,date,home_team,away_team,team,scorer,minute,own_goal,penalty
47886,2026-07-09,France,Morocco,France,Kylian Mbappé,60.0,False,False
47887,2026-07-09,France,Morocco,France,Ousmane Dembélé,66.0,False,False
47888,2026-07-10,Spain,Belgium,Spain,Fabián Ruiz,30.0,False,False
47889,2026-07-10,Spain,Belgium,Belgium,Charles De Ketelaere,41.0,False,False
47890,2026-07-10,Spain,Belgium,Spain,Mikel Merino,88.0,False,False

In [7]:
df.isnull().sum()

date           0
home_team      0
away_team      0
team           0
scorer        44
minute       254
own_goal       0
penalty        0
dtype: int64

In [29]:
df = df.dropna()

In [8]:
(df == 0).sum()

date             0
home_team        0
away_team        0
team             0
scorer           0
minute           0
own_goal     46955
penalty      44627
dtype: int64

In [26]:
df["date"] = pd.to_datetime(df["date"])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 47812 entries, 0 to 47890
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       47812 non-null  datetime64[ns]
 1   home_team  47812 non-null  object
 2   away_team  47812 non-null  object
 3   team       47812 non-null  object
 4   scorer     47802 non-null  object
 5   minute     47627 non-null  float64
 6   own_goal   47812 non-null  bool
 7   penalty    47812 non-null  bool
dtypes: bool(2), datetime64[ns](1), float64(1), object(4)
memory usage: 2.6+ MB

In [9]:
df.duplicated().sum()

np.int64(79)

In [10]:
df[df.duplicated(keep=False)].sort_values(list(df.columns))

,date,home_team,away_team,team,scorer,minute,own_goal,penalty
4059,1963-11-26,Ghana,Ethiopia,Ghana,Edward Acquah,NaN,False,False
4060,1963-11-26,Ghana,Ethiopia,Ghana,Edward Acquah,NaN,False,False
4063,1963-11-28,Ethiopia,Tunisia,Ethiopia,Mengistu Worku,NaN,False,False
4064,1963-11-28,Ethiopia,Tunisia,Ethiopia,Mengistu Worku,NaN,False,False
4067,1963-11-28,Nigeria,Sudan,Sudan,Nasr Eddin Abbas,NaN,False,False
...,...,...,...,...,...,...,...,...
41302,2021-09-05,San Marino,Poland,Poland,Adam Buksa,90.0,False,False
41775,2021-10-12,Syria,Lebanon,Lebanon,Mohamad Kdouh,45.0,False,False
41776,2021-10-12,Syria,Lebanon,Lebanon,Mohamad Kdouh,45.0,False,False
42832,2022-09-25,Moldova,Liechtenstein,Moldova,Victor Stînă,90.0,False,False
42833,2022-09-25,Moldova,Liechtenstein,Moldova,Victor Stînă,90.0,False,False

In [12]:
df = df.drop_duplicates() 
df.duplicated().sum()

np.int64(0)

In [15]:
sorted(df["team"].unique())

['Afghanistan',
 'Albania',
 'Algeria',
 'American Samoa',
 'Andorra',
 'Angola',
 'Anguilla',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Aruba',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'British Virgin Islands',
 'Brunei',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Cayman Islands',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo',
 'Cook Islands',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Curaçao',
 'Cyprus',
 'Czech Republic',
 'Czechoslovakia',
 'DR Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'England',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Eswatini',
 'Ethiopia',
 'Faroe Islands',
 'Fiji',
 'Finland',
 'France',
 'French Guiana',
 'Gabon',
 'Gambia',
 'Georgia',
 'German DR',
 'Germany',
 'Ghana',
 'Gibraltar',
 'Greece',
 'Grenada',
 'Guadeloupe',
 'Guam',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hong Kong',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Israel',
 'Italy',
 'Ivory Coast',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kosovo',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Macau',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Martinique',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Moldova',
 'Mongolia',
 'Montenegro',
 'Montserrat',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Netherlands',
 'New Caledonia',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'North Korea',
 'North Macedonia',
 'Northern Ireland',
 'Norway',
 'Oman',
 'Pakistan',
 'Palestine',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Republic of Ireland',
 'Romania',
 'Russia',
 'Rwanda',
 'Saarland',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'San Marino',
 'Saudi Arabia',
 'Scotland',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Korea',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Sweden',
 'Switzerland',
 'Syria',
 'São Tomé and Príncipe',
 'Tahiti',
 'Taiwan',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Timor-Leste',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Turks and Caicos Islands',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United States',
 'United States Virgin Islands',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela',
 'Vietnam',
 'Vietnam Republic',
 'Wales',
 'Yemen',
 'Yemen DPR',
 'Yugoslavia',
 'Zambia',
 'Zimbabwe']

In [32]:
df["team"].nunique()

205

In [18]:
times = df["minute"].sort_values().unique() 
times

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
       111., 112., 113., 114., 115., 116., 117., 118., 119., 120., 122.,
        nan])

In [23]:
df["own_goal"].value_counts()

own_goal
False    46876
True       936
Name: count, dtype: int64

In [24]:
df["penalty"].value_counts()

penalty
False    44548
True      3264
Name: count, dtype: int64

In [ ]:
remove_nonFIFA_teams = ["Comoros", "Czechoslovakia", "Faroe Islands", "French Guiana", "German DR", "Guadeloupe", 
                           "Kosovo", "Macau", "Martinique", "Papua New Guinea", "Saarland", "Tahiti", 
                           "Vietnam Republic", "Yemen DPR", "Yugoslavia"]

df = df[~df["team"].isin(remove_nonFIFA_teams)]
df = df[~df["home_team"].isin(remove_nonFIFA_teams) & ~df["away_team"].isin(remove_nonFIFA_teams)]

In [37]:
df.tail(20)

,date,home_team,away_team,team,scorer,minute,own_goal,penalty
47871,2026-07-05,Mexico,England,England,Jude Bellingham,38.0,False,False
47872,2026-07-05,Mexico,England,Mexico,Julián Quiñones,42.0,False,False
47873,2026-07-05,Mexico,England,England,Harry Kane,60.0,False,True
47874,2026-07-05,Mexico,England,Mexico,Raúl Jiménez,69.0,False,True
47875,2026-07-06,Portugal,Spain,Spain,Mikel Merino,90.0,False,False
47876,2026-07-06,United States,Belgium,Belgium,Charles De Ketelaere,9.0,False,False
47877,2026-07-06,United States,Belgium,United States,Malik Tillman,31.0,False,False
47878,2026-07-06,United States,Belgium,Belgium,Charles De Ketelaere,33.0,False,False
47879,2026-07-06,United States,Belgium,Belgium,Hans Vanaken,57.0,False,False
47880,2026-07-06,United States,Belgium,Belgium,Romelu Lukaku,90.0,False,False
47881,2026-07-07,Argentina,Egypt,Egypt,Yasser Ibrahim,15.0,False,False
47882,2026-07-07,Argentina,Egypt,Egypt,Mostafa Ziko,67.0,False,False
47883,2026-07-07,Argentina,Egypt,Argentina,Cristian Romero,79.0,False,False
47884,2026-07-07,Argentina,Egypt,Argentina,Lionel Messi,83.0,False,False
47885,2026-07-07,Argentina,Egypt,Argentina,Enzo Fernández,90.0,False,False
47886,2026-07-09,France,Morocco,France,Kylian Mbappé,60.0,False,False
47887,2026-07-09,France,Morocco,France,Ousmane Dembélé,66.0,False,False
47888,2026-07-10,Spain,Belgium,Spain,Fabián Ruiz,30.0,False,False
47889,2026-07-10,Spain,Belgium,Belgium,Charles De Ketelaere,41.0,False,False
47890,2026-07-10,Spain,Belgium,Spain,Mikel Merino,88.0,False,False

In [ ]:
df.to_csv(
    "../data/cleaned/goal_scorers_clean.csv",
    index = False
)####